import { createContext, useContext, useState } from 'react';

import { useEffect } from 'react';

// WARNING: NATIVE-SPEAKER VERIFICATION REQUIRED
// All Amharic (AM) strings below were machine-translated and have NOT been
// reviewed by a native Amharic speaker. Before public launch, every string in
// the AM object must be verified and corrected by a native speaker - especially
// financial/business terminology, verb forms, and formal/informal register.
// Do NOT ship to production without completing this review.

const EN = {
  installSectionTitle: 'Install App',
  installBannerTitle: 'Install Gebya on this phone',
  installBannerBody: 'Add Gebya to your home screen so you can open it like an app.',
  installNow: 'Install Now',
  installHowTo: 'Install',
  installGuideButton: 'How to install',
  installGuideTitle: 'Install Gebya on your phone',
  installGuideHint: 'Do this once, then open Gebya from your phone home screen.',
  installGuideDeviceTitle: 'Phone install steps',
  installAlreadyInstalled: 'Already installed',
  installStatusInstalled: 'Installed on your home screen',
  installStatusBrowser: 'Running in browser mode',
  installStatusOnline: 'Online now',
  installStatusOffline: 'Offline now',
  installChecklistOffline: 'Offline-ready notebook',
  installChecklistHomeScreen: 'Home screen install',
  installChecklistData: 'Data location',
  installChecklistReady: 'Ready',
  installChecklistInstalled: 'Installed',
  installChecklistPending: 'Not yet',
  installChecklistOnPhone: 'This phone',
  installIosStep1: 'Open Gebya in Safari.',
  installIosStep2: 'Tap Share, then tap "Add to Home Screen."',
  installIosStep3: 'Tap "Add", then open Gebya from your home screen.',
  installAndroidStep1: 'Open Gebya in Chrome.',
  installAndroidStep2: 'Open the browser menu and tap "Install app" or "Add to Home screen."',
  installAndroidStep3: 'Confirm, then open Gebya from your home screen.',
  installGenericStep1: 'Open Gebya in your phone browser.',
  installGenericStep2: 'Open the browser menu and look for "Install app" or "Add to Home Screen."',
  installGenericStep3: 'Save it, then open Gebya from your home screen.',
  updateReadyTitle: 'Fresh version ready',
  updateReadyBody: 'A newer app version is available. Refresh once to use the latest installable build.',
  refreshApp: 'Refresh App',
  offlineReadyTitle: 'Offline mode is ready',
  offlineReadyBody: 'Gebya can reopen even when your connection is weak, and your saved notebook stays on this phone.',
  offlineNowTitle: 'You are offline',
  offlineNowBody: 'Your saved notebook on this phone still works. Features that need internet may wait until you reconnect.',
  notNow: 'Not now',
  telegramNotifyConnectFirst: 'Connect Telegram first, then turn this on.',
  telegramConnectFirstToast: 'Connect Telegram first to send updates.',
  appName: 'Gebya',
  loading: 'Loading your notebook...',
  today: 'Today',
  todayLabel: 'Today',
  credit: 'Dubie',
  creditLabel: 'ዱቤ',
  partialPayment: 'Partial',
  report: 'Report',
  reminders: 'Reminders',
  settings: 'Settings',
  sales: 'Sales',
  spent: 'Spent',
  iSold: 'I Sold',
  iSoldLabel: 'Type Sale',
  iSpent: 'I Spent',
  iSpentLabel: 'I Spent',
  creditBtn: 'Dubie',
  creditBtnLabel: 'Dubie',
  calc: 'Calc',
  todaysEntries: "Today's Entries",
  noEntries: 'No entries yet. Use the buttons above to start!',
  profit: 'profit',
  edited: 'edited',
  editEntry: 'Edit entry',
  deleteEntryLabel: 'Delete entry',
  topProducts: 'Top Sold Today',
  weekTrend: '7-Day Trend',
  shareReport: 'Share Report',
  shareReportBtn: 'Share Today',
  shareTitle: 'Share Daily Report',
  shareDailyReport: 'Daily Report',
  shareTopItems: 'Top Items Sold',
  shareSentVia: 'Sent via Gebya',
  shareViaDevice: 'Share via Device',
  openTelegram: 'Open in Telegram',
  copyText: 'Copy Text',
  usageInsights: 'Usage Insights',
  dayStreak: 'day streak',
  best: 'best',
  daysActive: 'days active',
  since: 'since',
  totalEntries: 'entries',
  sessions: 'sessions opened',
  shareMyStats: 'Share My Stats',
  copiedToClipboard: 'Copied to clipboard!',
  shopProfile: 'Profile',
  userName: 'Name',
  phoneNumber: 'Phone Number',
  phoneRequired: 'Phone number is required',
  phoneInvalid: '9 digits starting with 7 or 9',
  telegramLabel: 'Telegram / Contact',
  telegramPlaceholder: '@username, t.me/... or https://t.me/...',
  connectTelegram: 'Connect Telegram',
  manageTelegram: 'Manage Telegram',
  telegramConnection: 'Telegram connection',
  telegramConnectHint: 'Link Telegram once, then turn on balance updates when you want.',
  telegramConnectedHint: 'This customer can receive Telegram balance updates.',
  notifyOnTelegram: 'Notify on Telegram',
  notifyOnTelegramHint: 'Open Telegram automatically after saving Dubie or payment.',
  telegramNotifyEnabledState: 'Automatic Telegram opening is on for this customer.',
  telegramNotifyDisabledState: 'Telegram stays optional and will not open automatically.',
  telegramNeedContactHint: 'Add a Telegram username or link first, then turn notifications on.',
  telegramFormatHint: 'Use only @username, t.me/... or https://t.me/...',
  telegramAutoUpdatesTitle: 'Automatic balance updates',
  telegramAutoUpdatesBody: 'Once linked, this customer can receive Telegram updates whenever their balance changes.',
  qrPrimaryMethod: 'QR code',
  telegramQrHint: 'Let the customer scan this QR code to open the Telegram connection link.',
  shareInviteLink: 'Share invite link',
  shareInviteLinkHint: 'Copy this link and send it through any channel you already use.',
  copyLink: 'Copy link',
  inviteLinkCopied: 'Invite link copied',
  copyFailed: 'Could not copy link',
  manualTelegramFallback: 'Manual fallback',
  manualTelegramFallbackHint: 'If needed, enter the customer Telegram username or t.me link manually.',
  sharePhonePrompt: 'Phone for shared receipts',
  sharePhoneHint: 'Include your phone number in shared sales',
  confirmConnection: 'Confirm Connection',
  skipForNow: 'Skip for Now',
  saveChanges: 'Save Changes',
  saved: 'Saved!',
  privacy: 'Privacy',
  hideAmounts: 'Hide amounts',
  totalsHidden: 'Totals are hidden - tap to show',
  totalsVisible: 'Totals are visible - tap to hide',
  paymentMethods: 'Payment Methods',
  banks: 'Banks',
  mobileWallets: 'Mobile Wallets',
  onlyEnabled: 'Only enabled methods appear as options in the form',
  recurringExpenses: 'Recurring Expenses',
  recurringHint: 'Quick-fill shortcuts for expenses you enter often',
  addRecurring: 'Add recurring expense',
  demoCardSectionLabel: 'Quick-fill (examples)',
  addRecurringPopupGuide: 'Save this as a recurring expense to reuse it anytime',
  addAndUse: 'Add & Use',
  addRecurringHint: 'You can add more recurring expenses in Settings',
  frequency: 'Frequency',
  cancel: 'Cancel',
  add: 'Add',
  yourData: 'Your Data',
  storedOnDevice: 'Stored on this device',
  exportCSV: 'Export to CSV',
  exportHint: 'Download a spreadsheet backup',
  exportFailed: 'Export failed',
  clearAll: 'Clear all data',
  clearHint: 'Permanently deletes everything - export first!',
  about: 'About',
  privacyNote: 'Your data never leaves this device. No account needed.',
  worksOffline: 'Works offline - data stays on your phone - free',
  achievementBadges: 'Achievement Badges',
  badgesEarned: 'earned',
  noBadges: 'Complete milestones to earn badges!',
  clearConfirm: 'Clear all data?',
  clearConfirmMsg: 'This will permanently delete all {count} entries and {credits} Dubie records. This cannot be undone.',
  yesDelete: 'Yes, delete everything',
  dataCleared: 'Data cleared',
  reloading: 'Reloading...',
  deleteEntry: 'Delete this entry?',
  delete: 'Delete',
  newBestDay: 'New best day!',
  birr: 'birr',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  expenseName: 'Expense name (e.g. Rent)',
  amount: 'Amount',
  sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat',

  onboardWelcome: 'Start your notebook',
  onboardSubtitle: 'Your business notebook',
  onboardTagline: 'Your shop notebook',
  onboardDesc: 'Enter your name and start using Gebya right away.',
  onboardNamePlaceholder: 'e.g. Tigist',
  onboardPhoneOptional: '(optional)',
  onboardPhoneHelper: 'You can add your phone later in Settings.',
  onboardPromiseSimple: 'Simple notebook for sales, spending, and Dubie',
  onboardPromiseFast: 'Start with your name only',
  onboardPromisePrivate: 'Your records stay on this phone',
  onboardGetStarted: 'Start using Gebya',
  onboardSettingUp: 'Setting up…',
  onboardFooter: 'All data stays on your phone · Not connected with your bank · Free',

  iSoldSomething: 'I Sold Something',
  iSpentSomething: 'I Spent Something',
  recordCredit: 'Record Dubie',
  addCredit: 'Add Dubie',
  addCustomer: 'Add Customer',
  saveCustomer: 'Save customer',
  customerSaved: 'Customer saved',
  customerSaveFailed: 'Could not save customer. Please try again.',
  customerHelperText: 'Use any label you will recognize later.',
  customerIdentifier: 'Customer identifier',
  customerIdentifierPlaceholder: 'Name, nickname, relation, place, or vehicle clue',
  customerNotePlaceholder: 'Anything that helps you recognize this customer',
  customerPhoneOptional: 'Phone (optional)',
  customerPhonePlaceholder: 'Phone number',
  customerTelegramOptional: 'Telegram (optional)',
  customerTelegramPlaceholder: '@username, t.me/... or https://t.me/...',
  customerTotalBalance: 'Total Balance',
  customerBalance: 'Balance',
  searchCustomerPlaceholder: 'Search customer or note...',
  customerSearchHint: 'Search by name, note, phone, or Telegram.',
  customerSearchResults: 'Showing {shown} of {total} customers',
  noCustomersFound: 'No customers found',
  noCustomersYet: 'No customers yet',
  noCustomerSearchResults: 'No customers match this search',
  backToCustomers: 'Back to customers',
  customerTransactionHistory: 'Transaction History',
  paymentRecordedLabel: 'Payment',
  creditAddedLabel: 'Dubie added',
  noTransactionsYet: 'No transactions yet',
  noTransactionsHint: 'Use Add Dubie or Record Payment to start this history.',
  currentBalance: 'Current Balance',
  previousBalance: 'Previous balance',
  updatedBalance: 'Updated balance',
  currentBalanceHint: 'This is the balance after saving the new Dubie.',
  remainingBalanceHint: 'This is the remaining balance after saving the payment.',
  paymentNoteOptional: 'Payment note (optional)',
  itemNoteOptional: 'Item note (optional)',
  paymentNotePlaceholder: 'Any note about this payment',
  creditItemPlaceholder: 'What they took',
  dueDateOptional: 'Due date (optional)',
  ethiopianDisplay: 'Ethiopian display',
  pickDateWithEthiopianHint: 'Choose any date below and we will also show it in Ethiopian calendar.',
  moreOptional: 'More (optional)',
  noteLabel: 'Note',
  savePayment: 'Save payment',
  customerNotFound: 'Customer not found',
  validAmountRequired: 'Enter a valid amount',
  paymentMoreThanBalance: 'Payment is more than the current balance',
  noBalanceToRecordPayment: 'No balance to collect yet',
  balanceAfterEntry: 'Balance after this entry',
  dueLabelShort: 'Due',
  whatDidYouSell: 'What did you sell?',
  sellPlaceholder: 'Add details...',
  whatDidYouSpendOn: 'What did you spend on?',
  spendPlaceholder: 'Add details...',
  creditNameLabel: 'Name',
  creditNamePlaceholder: 'e.g. Abebe...',
  howMuchTotal: 'How much total?',
  saveSale: 'Save Sale',
  saveExpense: 'Save Expense',
  saveCredit: 'Save Dubie',
  addAnotherSale: 'Add another sale',
  done: 'Done',
  birrSaved: 'birr saved',
  howMany: 'How many?',
  direction: 'Direction',
  theyOweMe: 'They owe me',
  iOweThem: 'I owe them',
  owesMe: 'Owes me',
  iOweLabel: 'I owe',
  quickFill: 'Quick-fill',
  phoneOptional: 'Phone number',
  phoneOptionalHint: '(optional)',
  phonePlaceholder: 'e.g. 0912345678',
  whenDue: 'When is it due?',
  pickDate: 'Pick a date',
  selectDueDate: 'Please select a due date',
  advancedOptional: 'Advanced (optional)',
  whatDidYouPay: 'What did you pay for this?',
  perUnit: '(per unit)',
  helpsSeeProfit: 'Optional - helps you see your true profit',
  sellingBelowCost: 'You are selling below cost. You may lose money on this sale.',
  profitOnSale: 'Profit on this sale:',
  paymentType: 'Payment type',
  cash: 'Cash',
  bank: 'Bank',
  wallet: 'Wallet',

  editSale: 'Edit Sale',
  editExpense: 'Edit Expense',
  editCredit: 'Edit Dubie',
  editEntryLabel: 'Edit Entry',
  editedAt: 'Edited',
  item: 'Item',
  quantity: 'Quantity',
  dueDate: 'Due date',
  costPriceLabel: 'Cost price',
  sellingBelowCostShort: 'Selling below cost.',
  profitLabel: 'Profit:',
  saving: 'Saving...',

  todaysProfit: "Today's Profit",
  estimatedProfit: "Estimated Profit",
  partialCostDisclaimer: "Some items are missing a cost price - this estimate may be lower than your actual profit",
  partialCostTip: "Add cost prices to your items for an accurate profit figure",
  todaysSales: "Today's Sales",
  salesLabel: 'Sales',
  expenses: 'Expenses',
  costOfGoods: 'Cost of goods',
  netProfit: 'Net Profit',
  advancedHint: 'Tap "Advanced" when recording a sale to see true profit',

  tapToReveal: 'Tap to reveal',
  tapToRevealAria: 'Tap to reveal amount',
  hideAmountAria: 'Hide amount',

  byDay: 'By Day',
  byWeek: 'By Week',
  groupBy: 'Group:',
  searchPlaceholder: 'Search by item or customer...',
  noSearchResults: 'No results for',
  noRecords: 'No records yet',
  startRecording: 'Record your first sale or expense to start',
  entries: 'entries',
  revenue: 'revenue',
  thisWeek: 'This Week',

  noCreditRecords: 'No Dubie records',
  addCreditHint: 'Tap "Dubie" on the Today tab to add one',
  owedToMe: 'Owed to me',
  iOweAmount: 'I owe',
  active: 'active',
  paid: 'paid',
  activeTab: 'Active',
  paidTab: 'Paid',
  noPaidRecords: 'No paid records yet',
  allCaughtUp: 'All caught up!',
  paidInFull: 'Paid in full',
  paidLabel: 'PAID',
  due: 'Due',
  owesMeLabel: 'Owes me',
  iOweTag: 'I owe',

  backToCredit: 'Back to Dubie',
  originalDebt: 'Original debt',
  amountPaid: 'Amount paid',
  stillOwes: 'Still owes',
  progress: 'Progress',
  percentPaid: '% paid',
  paidSome: 'Paid Some',
  allPaid: 'All Paid',
  call: 'Call',
  recordPartialPayment: 'Record Partial Payment',
  recordPayment: 'Record Payment',
  markFullyPaid: 'Mark Fully Paid',
  paymentHistory: 'Payment history',
  borrowed: 'Borrowed',
  paidBack: 'Paid back',
  remaining: 'Remaining',
  payMethodCash: 'Cash',
  payMethodBank: 'Bank Transfer',
  payMethodMobile: 'Mobile Money',
  paymentExceedsOwed: 'Amount cannot exceed what is owed',

  tryAgain: 'Try again',

  close: 'Close',

  todaysBreakdown: "Today's Breakdown",
  payingVia: 'Paying via',
  creditPhoneHint: '9 digits starting with 7 or 9',
  addCustomBank: 'Add bank...',
  addCustomWallet: 'Add wallet...',
  customProviderName: 'Provider name',
  providerEnabled: 'Enabled',
  providerDisabled: 'Disabled',

  introSlide1Title: 'Your Business Notebook',
  introSlide1Body: 'Track sales, expenses, and Dubie - all on your phone. No account needed.',
  introSlide2Title: 'See Your Money at a Glance',
  introSlide2Body: "Today's profit always shows at the top. Know where you stand in seconds.",
  introSlide3Title: 'Three Buttons. That\'s It.',
  introSlide3Body: 'Tap Type Sale to sell, I Spent to record spending, and Dubie to track credit. Done in 10 seconds.',
  introLetsStart: "Let's start",
  introNext: 'Next ->',
  introSkip: 'Skip intro',

  noEntriesPrompt: 'Tap Type Sale above to record your first sale',

  saleSaved: 'Sale saved - keep going',
  expenseSaved: 'Expense recorded',
  creditSaved: 'Dubie recorded',
  paymentSaved: 'Payment recorded',
  trustCardTitle: 'Your notebook stays on this phone',
  trustCardBody: 'Save your sales, close the app, and open again later. Your records stay here on this phone.',
  trustCardAction: 'Record your first sale',
  trustLastSaved: 'Last saved',
  trustTodayCount: 'saved today',
  trustReopenHint: 'Close and reopen anytime - your records stay here.',
  undone: 'Undone',

  statusOverdue: 'OVERDUE',
  statusDueSoon: 'DUE SOON',
  statusOk: 'OK',

  periodDay: 'Day',
  periodWeek: 'Week',
  periodMonth: 'Month',
  totalSales: 'Total Sales',
  totalExpenses: 'Total Expenses',
  topProductsWeek: 'Top Products This Week',
  topProductsMonth: 'Top Products This Month',
  topProductsDay: 'Top Products Today',
  byQuantity: 'by qty',
  byRevenue: 'by revenue',
  weekBreakdown: 'Day-by-Day',
  monthBreakdown: 'Week-by-Week',
  weekOf: 'Week of',
  noSalesThisPeriod: 'No sales this period',
  week: 'Wk',

  typeSale: 'Type Sale',
  typeSaleLabel: 'Type Sale',
};

// Install-related Amharic strings below require human review before public beta:
// installSectionTitle, installBannerTitle, installBannerBody, installNow, installHowTo,
// installGuideButton, installGuideTitle, installGuideHint, installGuideDeviceTitle,
// installAlreadyInstalled, installStatusInstalled, installStatusBrowser,
// installStatusOnline, installStatusOffline, installChecklistOffline,
// installChecklistHomeScreen, installChecklistData, installChecklistReady,
// installChecklistInstalled, installChecklistPending, installChecklistOnPhone,
// installIosStep1, installIosStep2, installIosStep3, installAndroidStep1,
// installAndroidStep2, installAndroidStep3, installGenericStep1,
// installGenericStep2, installGenericStep3.
const AM = {
  installSectionTitle: 'መተግበሪያ ጫን',
  installBannerTitle: 'ገበያን በዚህ ስልክ ላይ ጫን',
  installBannerBody: 'ገበያን ወደ መነሻ ገጽ ያስቀምጡት እና እንደ መተግበሪያ ይክፈቱት።',
  installNow: 'አሁን ጫን',
  installHowTo: 'ጫን',
  installGuideButton: 'እንዴት እንደሚጫን',
  installGuideTitle: 'ገበያን በስልክዎ ላይ ጫን',
  installGuideHint: 'አንድ ጊዜ ብቻ ይህን ያድርጉ፣ ከዚያ ገበያን ከመነሻ ገጽ ይክፈቱት።',
  installGuideDeviceTitle: 'የስልክ ጫን እርምጃዎች',
  installAlreadyInstalled: 'አስቀድሞ ተጭኗል',
  installStatusInstalled: 'በመነሻ ገጽ ላይ ተጭኗል',
  installStatusBrowser: 'በብራውዘር ውስጥ እየሰራ ነው',
  installStatusOnline: 'አሁን ኢንተርኔት አለ',
  installStatusOffline: 'አሁን ከኢንተርኔት ውጪ ነው',
  installChecklistOffline: 'ከኢንተርኔት ውጪ የሚሰራ ማስታወሻ',
  installChecklistHomeScreen: 'የመነሻ ገጽ ጫን',
  installChecklistData: 'የውሂብ ቦታ',
  installChecklistReady: 'ዝግጁ',
  installChecklistInstalled: 'ተጭኗል',
  installChecklistPending: 'ገና አይደለም',
  installChecklistOnPhone: 'በዚህ ስልክ',
  installIosStep1: 'ገበያን በ iPhone Safari ውስጥ ይክፈቱት።',
  installIosStep2: 'የማጋራት ቁልፉን ይጫኑ፣ ከዚያ "Add to Home Screen" ይምረጡ።',
  installIosStep3: '"Add" ይጫኑ፣ ከዚያ ገበያን ከመነሻ ገጽ ይክፈቱት።',
  installAndroidStep1: 'ገበያን በ Android Chrome ውስጥ ይክፈቱት።',
  installAndroidStep2: 'የብራውዘር ምናሌ ይክፈቱ፣ ከዚያ "Install app" ወይም "Add to Home screen" ይጫኑ።',
  installAndroidStep3: 'ያረጋግጡ፣ ከዚያ ገበያን ከመነሻ ገጽ ይክፈቱት።',
  installGenericStep1: 'ገበያን በስልክዎ ብራውዘር ይክፈቱት።',
  installGenericStep2: 'የብራውዘር ምናሌ ይክፈቱ እና "Install app" ወይም "Add to Home Screen" ይፈልጉ።',
  installGenericStep3: 'ያስቀምጡት፣ ከዚያ ገበያን ከመነሻ ገጽ ይክፈቱት።',
  updateReadyTitle: 'አዲስ እትም ዝግጁ ነው',
  updateReadyBody: 'አዲስ የመተግበሪያ እትም አለ። አንድ ጊዜ ያድሱ።',
  refreshApp: 'መተግበሪያውን አድስ',
  offlineReadyTitle: 'የኦፍላይን አጠቃቀም ዝግጁ ነው',
  offlineReadyBody: 'ግንኙነት ቢደክምም ገበያን እንደገና መክፈት ይችላሉ፣ መዝገቦችዎም በዚህ ስልክ ላይ ይቆያሉ።',
  offlineNowTitle: 'አሁን ከኢንተርኔት ውጪ ነዎት',
  offlineNowBody: 'በዚህ ስልክ ላይ የተቀመጠው ማስታወሻ እንደተለመደው ይሰራል።',
  notNow: 'አሁን አይደለም',
  telegramNotifyConnectFirst: 'ቴሌግራምን በመጀመሪያ ያገናኙ፣ ከዚያ ይህን ያብሩ።',
  telegramConnectFirstToast: 'ዝመና ለመላክ ቴሌግራምን በመጀመሪያ ያገናኙ።',
  appName: 'ገበያ',
  loading: 'ማስታወሻዎን በመጫን ላይ…',
  today: 'ዛሬ',
  todayLabel: 'ዛሬ',
  credit: 'ዱቤ',
  creditLabel: 'ዱቤ',
  report: 'ሪፖርት',
  settings: 'ቅንብሮች',
  sales: 'ሽያጭ',
  spent: 'ወጪ',
  iSold: 'ሸጥ',
  iSoldLabel: 'ሸጥ',
  iSpent: 'ወጪ',
  iSpentLabel: 'ወጪ',
  creditBtn: 'ዱቤ',
  creditBtnLabel: 'ዱቤ',
  calc: 'አስሊ',
  todaysEntries: 'የዛሬ ግቤቶች',
  noEntries: 'ገና ምንም ግቤት የለም። ለመጀመር ከላይ ያሉትን ቁልፎች ይጫኑ።',
  profit: 'ትርፍ',
  edited: 'ተስተካክሏል',
  editEntry: 'ለማስተካክል',
  deleteEntryLabel: 'ግቤት ሰርዝ',
  topProducts: 'ዛሬ ምርጥ ሽያጭ',
  weekTrend: 'የ7 ቀን አዝማሚያ',
  shareReport: 'ሪፖርት አጋራ',
  shareReportBtn: 'ዛሬን አጋራ',
  shareTitle: 'ዕለታዊ ሪፖርት አጋራ',
  shareDailyReport: 'ዕለታዊ ሪፖርት',
  shareTopItems: 'ምርጥ ሽያጭ',
  shareSentVia: 'በ ገበያ (Gebya) ተልኳል',
  shareViaDevice: 'በስልክ አጋራ',
  openTelegram: 'ቴሌግራም ክፈት',
  copyText: 'ጽሑፍ ቅዳ',
  usageInsights: 'የአጠቃቀም ዝርዝር',
  dayStreak: 'ቀን ተከታታይ',
  best: 'ምርጥ',
  daysActive: 'ንቁ ቀናት',
  since: 'ጀምሮ',
  totalEntries: 'ግቤቶች',
  sessions: 'ክፍለ ጊዜ',
  shareMyStats: 'ስታቲስቲክስን አጋራ',
  copiedToClipboard: 'ወደ ቅጂ ተገልብጧል',
  shopProfile: 'መገለጫ',
  userName: 'ስም',
  phoneNumber: 'ስልክ ቁጥር',
  phoneRequired: 'ስልክ ቁጥር ያስፈልጋል',
  phoneInvalid: '9 አሃዞች በ7 ወይም 9 የሚጀምሩ',
  telegramLabel: 'ቴሌግራም / ግንኙነት',
  telegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  connectTelegram: 'ቴሌግራም አገናኝ',
  manageTelegram: 'ቴሌግራም አስተዳድር',
  telegramConnection: 'የቴሌግራም ግንኙነት',
  telegramConnectHint: 'አንድ ጊዜ ቴሌግራም ያገናኙ፣ ከዚያ ሲፈልጉ የቀሪ ሂሳብ ማሳወቂያ ያብሩ።',
  telegramConnectedHint: 'ይህ ደንበኛ በቴሌግራም የቀሪ ሂሳብ መልእክት ሊደርሰው ይችላል።',
  notifyOnTelegram: 'በቴሌግራም አሳውቅ',
  notifyOnTelegramHint: 'ዱቤ ወይም ክፍያ ከተመዘገበ በኋላ ቴሌግራም ራሱን ይከፍታል።',
  telegramNotifyEnabledState: 'ለዚህ ደንበኛ ራስ-ሰር የቴሌግራም መክፈት ነቅቷል።',
  telegramNotifyDisabledState: 'ቴሌግራም አማራጭ ብቻ ነው፣ ራሱን አይከፍትም።',
  telegramNeedContactHint: 'መጀመሪያ የቴሌግራም ስም ወይም ሊንክ ያስገቡ።',
  telegramFormatHint: '@username, t.me/... ወይም https://t.me/... ብቻ ይጠቀሙ።',
  telegramAutoUpdatesTitle: 'ራስ-ሰር የቀሪ ሂሳብ ማሳወቂያ',
  telegramAutoUpdatesBody: 'ከተገናኝ በኋላ የዚህ ደንበኛ ቀሪ ሂሳብ ሲቀየር በቴሌግራም መልእክት ሊደርሰው ይችላል።',
  qrPrimaryMethod: 'QR ኮድ',
  telegramQrHint: 'ይህንን QR ኮድ እንዲስካን አድርጉት እና የቴሌግራም ግንኙነት ሊንኩን ይክፈት።',
  shareInviteLink: 'የግብዣ ሊንክ አጋራ',
  shareInviteLinkHint: 'ይህንን ሊንክ ቅዳ እና በሚጠቀሙበት ማንኛውም መንገድ ላክ።',
  copyLink: 'ሊንክ ቅዳ',
  inviteLinkCopied: 'የግብዣ ሊንክ ተቀድቷል',
  copyFailed: 'ሊንኩን መቅዳት አልተቻለም',
  manualTelegramFallback: 'በእጅ ማስገባት',
  manualTelegramFallbackHint: 'ካስፈለገ የደንበኛውን @username ወይም t.me ሊንክ በእጅ ያስገቡ።',
  sharePhonePrompt: 'ለመጋራት ስልክ ቁጥር',
  sharePhoneHint: 'የስልክ ቁጥርዎን በተጋራት ሽያጭ ውስጥ ያካትቱ',
  confirmConnection: 'ግንኙነቱን አረጋግጥ',
  skipForNow: 'ለአሁን ዝለል',
  saveChanges: 'ለውጦችን አስቀምጥ',
  saved: 'ተቀምጧል',
  privacy: 'ግላዊነት',
  hideAmounts: 'ቁጥሮችን ደብቅ',
  totalsHidden: 'ጠቅላላዎቹ ተደብቀዋል — ለማሳየት ይጫኑ',
  totalsVisible: 'ጠቅላላዎቹ ይታያሉ — ለመደበቅ ይጫኑ',
  paymentMethods: 'የክፍያ ዘዴዎች',
  banks: 'ባንኮች',
  mobileWallets: 'ሞባይል ዋሌት',
  onlyEnabled: 'የነቁ ዘዴዎች ብቻ በቅጹ ውስጥ ይታያሉ',
  recurringExpenses: 'ተደጋጋሚ ወጪዎች',
  recurringHint: 'ብዙ ጊዜ ለሚያስገቡዋቸው ወጪዎች ፈጣን ቅጽ',
  addRecurring: 'ተደጋጋሚ ወጪ አክል',
  demoCardSectionLabel: 'ፈጣን ሙላ (ምሳሌዎች)',
  addRecurringPopupGuide: 'ይህን ወጪ ለሚቀጥሉ ጊዜያት አስቀምጥ',
  addAndUse: 'አስቀምጥ እና ተጠቀም',
  addRecurringHint: 'ሌሎች ተደጋጋሚ ወጪዎችን በቅንብሮች ውስጥ ማከል ይችላሉ',
  frequency: 'ድግግሞሽ',
  cancel: 'ሰርዝ',
  add: 'አክል',
  yourData: 'የእርስዎ ውሂብ',
  storedOnDevice: 'በዚህ ስልክ ላይ ተቀምጧል',
  exportCSV: 'CSV ወደ ውጭ ላክ',
  exportHint: 'ስፕሬድሺት ምትኬ ያውርዱ',
  clearAll: 'ሁሉንም ውሂብ አጥፋ',
  clearHint: 'ሁሉም ነገር ሙሉ በሙሉ ይሰረዛል — መጀመሪያ ይልኩ!',
  about: 'ስለ ፕሮግራሙ',
  privacyNote: 'ውሂቡ ከዚህ ስልክ አይወጣም። ምዝገባ አያስፈልግም።',
  worksOffline: 'ከኢንተርኔት ውጪም ይሰራል · ውሂቡ በስልክዎ ላይ ይቆያል · ነፃ',
  achievementBadges: 'የስኬት ባጆች',
  badgesEarned: 'ተገኝቷል',
  noBadges: 'ባጆች ለማግኘት ኢላማዎችን ያሟሉ!',
  clearConfirm: 'ሁሉንም ውሂብ አጥፋ?',
  clearConfirmMsg: 'ይህ ሁሉን {count} ግቤቶችና {credits} የዱቤ መዝገቦችን ሙሉ በሙሉ ይሰርዛል። ሊቀለበስ አይችልም።',
  yesDelete: 'አዎ፣ ሁሉንም ሰርዝ',
  dataCleared: 'ውሂቡ ተሰርዟል',
  reloading: 'እንደገና በመጫን ላይ…',
  deleteEntry: 'ይህንን ግቤት ይሰርዙ?',
  delete: 'ሰርዝ',
  newBestDay: 'አዲስ ምርጥ ቀን',
  birr: 'ብር',
  daily: 'ዕለታዊ',
  weekly: 'ሳምንታዊ',
  monthly: 'ወርሃዊ',
  expenseName: 'የወጪ ስም (ለምሳሌ ኪራይ)',
  amount: 'መጠን',
  sun: 'እሁድ', mon: 'ሰኞ', tue: 'ማክሰ', wed: 'ረቡዕ', thu: 'ሐሙስ', fri: 'አርብ', sat: 'ቅዳሜ',

  onboardWelcome: 'ማስታወሻዎን ጀምር',
  onboardSubtitle: 'የሱቅ ማስታወሻ',
  onboardTagline: 'የሱቅ ማስታወሻ ደብተር',
  onboardDesc: 'ስምዎን ያስገቡና ገበያን ወዲያው ይጀምሩ።',
  onboardNamePlaceholder: 'ለምሳሌ ትግስት',
  onboardPhoneOptional: '(አማራጭ)',
  onboardPhoneHelper: 'ስልክዎን በቅንብሮች ውስጥ በኋላ ማከል ይችላሉ።',
  onboardPromiseSimple: 'ለሽያጭ፣ ወጪ እና ዱቤ ቀላል ማስታወሻ',
  onboardPromiseFast: 'በስምዎ ብቻ ይጀምሩ',
  onboardPromisePrivate: 'መዝገቦችዎ በዚህ ስልክ ላይ ይቆያሉ',
  onboardGetStarted: 'ገበያን ጀምር',
  onboardSettingUp: 'በማዘጋጀት ላይ…',
  onboardFooter: 'መረጃዎ በስልክዎ ላይ ይቆያል · ከባንክ ጋር አልተገናኘም · ነፃ',

  iSoldSomething: 'ሸጥኩ',
  iSpentSomething: 'ወጪ',
  recordCredit: 'ዱቤ መዝግብ',
  addCredit: 'ዱቤ አክል',
  addCustomer: 'ደንበኛ ጨምር',
  saveCustomer: 'ደንበኛ አስቀምጥ',
  customerSaved: 'ደንበኛ ተቀምጧል',
  customerSaveFailed: 'ደንበኛውን ማስቀመጥ አልተቻለም። እባክዎ ድጋሜ ይሞክሩ።',
  customerHelperText: 'በኋላ የሚያስታውሱትን ማንኛውም መለያ ይጠቀሙ።',
  customerIdentifier: 'የደንበኛ መለያ',
  customerIdentifierPlaceholder: 'ስም፣ ቅጽል፣ ዝምድና፣ ቦታ ወይም ምልክት',
  customerNotePlaceholder: 'ይህንን ደንበኛ ለማስታወስ የሚረዳ ማስታወሻ',
  customerPhoneOptional: 'ስልክ (አማራጭ)',
  customerPhonePlaceholder: 'ስልክ ቁጥር',
  customerTelegramOptional: 'ቴሌግራም (አማራጭ)',
  customerTelegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  customerTotalBalance: 'ጠቅላላ ቀሪ ሂሳብ',
  customerBalance: 'ቀሪ ሂሳብ',
  searchCustomerPlaceholder: 'ደንበኛ ወይም ማስታወሻ ፈልግ…',
  customerSearchHint: 'በስም፣ በማስታወሻ፣ በስልክ ወይም በቴሌግራም ይፈልጉ።',
  customerSearchResults: 'ከ {total} ደንበኞች {shown} ታይተዋል',
  noCustomersFound: 'ምንም ደንበኞች አልተገኙም',
  noCustomersYet: 'ገና ምንም ደንበኞች የሉም',
  noCustomerSearchResults: 'ከዚህ ፍለጋ ጋር የሚዛመዱ ደንበኞች አልተገኙም',
  backToCustomers: 'ወደ ደንበኞች ተመለስ',
  customerTransactionHistory: 'የግብይት ታሪክ',
  paymentRecordedLabel: 'ክፍያ',
  creditAddedLabel: 'ዱቤ ተጨምሯል',
  noTransactionsYet: 'እስካሁን ምንም ግብይት የለም',
  noTransactionsHint: 'ይህንን ታሪክ ለመጀመር ዱቤ ጨምር ወይም ክፍያ መዝግብ ይጠቀሙ።',
  currentBalance: 'አሁን ያለ ቀሪ ሂሳብ',
  previousBalance: 'ያለፈው ቀሪ ሂሳብ',
  updatedBalance: 'የተሻሻለ ቀሪ ሂሳብ',
  currentBalanceHint: 'ይህ አዲሱን ዱቤ ካስቀመጡ በኋላ የሚታየው ቀሪ ሂሳብ ነው።',
  remainingBalanceHint: 'ይህ ክፍያውን ካስቀመጡ በኋላ የሚቀረው ቀሪ ሂሳብ ነው።',
  paymentNoteOptional: 'የክፍያ ማስታወሻ (አማራጭ)',
  itemNoteOptional: 'የተወሰደው ማስታወሻ (አማራጭ)',
  paymentNotePlaceholder: 'ስለዚህ ክፍያ ማንኛውም ማስታወሻ',
  creditItemPlaceholder: 'የወሰዱት ምንድን ነው',
  dueDateOptional: 'የመክፍያ ቀን (አማራጭ)',
  ethiopianDisplay: 'በኢትዮጵያ ቀን መቁጠሪያ',
  pickDateWithEthiopianHint: 'ቀን ይምረጡ፣ እንዲሁም በኢትዮጵያ ቀን መቁጠሪያ እናሳያለን።',
  moreOptional: 'ተጨማሪ (አማራጭ)',
  noteLabel: 'ማስታወሻ',
  savePayment: 'ክፍያ አስቀምጥ',
  customerNotFound: 'ደንበኛው አልተገኘም',
  validAmountRequired: 'ትክክለኛ መጠን ያስገቡ',
  paymentMoreThanBalance: 'ክፍያው ከአሁኑ ቀሪ ሂሳብ ይበልጣል',
  noBalanceToRecordPayment: 'ገና የሚሰበሰብ ቀሪ ሂሳብ የለም',
  balanceAfterEntry: 'ከዚህ ግቤት በኋላ ያለ ቀሪ ሂሳብ',
  dueLabelShort: 'መክፍያ',
  whatDidYouSell: 'ምን ሸጡ?',
  sellPlaceholder: 'ዝርዝሩን ይመዝቡ...',
  whatDidYouSpendOn: 'ምን ላይ ወጪ?',
  spendPlaceholder: 'ዝርዝሩን ይመዝቡ...',
  creditNameLabel: 'ስም',
  creditNamePlaceholder: 'ለምሳሌ አበበ…',
  howMuchTotal: 'ጠቅላላ ስንት?',
  saveSale: 'ሽያጭ አስቀምጥ',
  saveExpense: 'ወጪ አስቀምጥ',
  saveCredit: 'ዱቤ አስቀምጥ',
  addAnotherSale: 'ሌላ ሽያጭ አክል',
  done: 'ተጠናቀቀ',
  birrSaved: 'ብር ተቀምጧል',
  howMany: 'ስንት?',
  direction: 'አቅጣጫ',
  theyOweMe: 'ያበደርኩት',
  iOweThem: 'የተበደርኩት',
  owesMe: 'ያበደርኩት',
  iOweLabel: 'የተበደርኩት',
  quickFill: 'ፈጣን ሙላ',
  phoneOptional: 'ስልክ ቁጥር',
  phoneOptionalHint: '(አማራጭ)',
  phonePlaceholder: 'ለምሳሌ 0912345678',
  whenDue: 'መቼ ይከፍላል?',
  pickDate: 'ቀን ምረጥ',
  selectDueDate: 'የመክፍያ ቀን ይምረጡ',
  advancedOptional: 'ተጨማሪ (አማራጭ)',
  whatDidYouPay: 'ለዚህ ምን ከፈሉ?',
  perUnit: '(በአንድ)',
  helpsSeeProfit: 'አማራጭ — ትክክለኛውን ትርፍ ለማየት ይረዳል',
  sellingBelowCost: 'ከዋጋ በታች እየሸጡ ነው። ኪሳራ ሊደርስ ይችላል።',
  profitOnSale: 'በዚህ ሽያጭ ትርፍ:',
  paymentType: 'የክፍያ አይነት',
  cash: 'ጥሬ ገንዘብ',
  bank: 'ባንክ',
  wallet: 'ዋሌት',

  editSale: 'ሽያጭ አርትዕ',
  editExpense: 'ወጪ አርትዕ',
  editCredit: 'ዱቤ አርትዕ',
  editEntryLabel: 'ግቤት አርትዕ',
  editedAt: 'ተስተካክሏል',
  item: 'እቃ',
  quantity: 'ብዛት',
  dueDate: 'የመክፍያ ቀን',
  costPriceLabel: 'የዋጋ',
  sellingBelowCostShort: 'ከዋጋ በታች።',
  profitLabel: 'ትርፍ:',
  saving: 'እየተቀመጠ…',

  todaysProfit: 'የዛሬ ትርፍ',
  estimatedProfit: 'የተገመተ ትርፍ',
  partialCostDisclaimer: 'አንዳንድ እቃዎች የዋጋ መረጃ ጎድሏቸዋል — ይህ ግምት ከትክክለኛው ትርፍ ያነሰ ሊሆን ይችላል',
  partialCostTip: 'ትክክለኛ ትርፍ ለማየት ለእቃዎቹ የዋጋ ያስገቡ',
  todaysSales: 'የዛሬ ሽያጭ',
  salesLabel: 'ሽያጭ',
  expenses: 'ወጪዎች',
  costOfGoods: 'የእቃ ዋጋ',
  netProfit: 'ንጹህ ትርፍ',
  advancedHint: 'ትክክለኛውን ትርፍ ለማየት ሽያጭ ሲመዘግቡ "ተጨማሪ" ይጫኑ',

  tapToReveal: 'ለማሳየት ይጫኑ',
  tapToRevealAria: 'መጠንን ለማሳየት ይጫኑ',
  hideAmountAria: 'መጠንን ደብቅ',

  byDay: 'በቀን',
  byWeek: 'በሳምንት',
  groupBy: 'ቡድን:',
  searchPlaceholder: 'በእቃ ወይም ደንበኛ ፈልግ…',
  noSearchResults: 'ምንም ውጤት',
  noRecords: 'እስካሁን ምንም መዝገብ የለም',
  startRecording: 'ለመጀመር የመጀመሪያ ሽያጭ ወይም ወጪ ይመዝግቡ',
  entries: 'ግቤቶች',
  revenue: 'ገቢ',
  thisWeek: 'ይህ ሳምንት',

  noCreditRecords: 'የዱቤ መዝገብ የለም',
  addCreditHint: 'ዱቤ ለማክል በዛሬ ገጽ ላይ "ዱቤ" ይጫኑ',
  owedToMe: 'ያበደርኩት',
  iOweAmount: 'የተበደርኩት',
  active: 'ንቁ',
  paid: 'የተከፈለ',
  activeTab: 'ንቁ',
  paidTab: 'የተከፈለ',
  noPaidRecords: 'እስካሁን የተከፈለ መዝገብ የለም',
  allCaughtUp: 'ሁሉም ተከፍሏል!',
  paidInFull: 'ሙሉ በሙሉ ተከፍሏል',
  paidLabel: 'ተከፍሏል',
  due: 'መክፍያ',
  owesMeLabel: 'ያበደርኩት',
  iOweTag: 'የተበደርኩት',

  backToCredit: 'ወደ ዱቤ ተመለስ',
  originalDebt: 'ዋና ዕዳ',
  amountPaid: 'የተከፈለ',
  stillOwes: 'ቀሪ ዕዳ',
  progress: 'ሂደት',
  percentPaid: '% ተከፍሏል',
  paidSome: 'ከፊል ክፍያ',
  allPaid: 'ሙሉ ተከፍሏል',
  call: 'ደውል',
  recordPartialPayment: 'ከፊል ክፍያ መዝግብ',
  recordPayment: 'ክፍያ መዝግብ',
  markFullyPaid: 'ሙሉ ተከፍሏል ብለህ አድርግ',
  paymentHistory: 'የክፍያ ታሪክ',
  borrowed: 'የተበደረ',
  paidBack: 'የተመለሰ',
  remaining: 'ቀሪ',
  payMethodCash: 'ጥሬ ገንዘብ',
  payMethodBank: 'ባንክ ዝውውር',
  payMethodMobile: 'ሞባይል ገንዘብ',
  paymentExceedsOwed: 'መጠኑ ከሚገባው መጠን ሊበልጥ አይችልም',

  tryAgain: 'እንደገና ሞክር',

  close: 'ዝጋ',

  todaysBreakdown: 'የዛሬ ሂሳብ',
  payingVia: 'በ',
  creditPhoneHint: '9 አሃዞች፣ ከ7 ወይም 9 ይጀምሩ',
  addCustomBank: 'ባንክ አክል…',
  addCustomWallet: 'ዋሌት አክል…',
  customProviderName: 'ስም',
  providerEnabled: 'ነቅቷል',
  providerDisabled: 'ተዘግቷል',

  introSlide1Title: 'የሱቅ ማስታወሻ',
  introSlide1Body: 'ሽያጭ፣ ወጪ እና ዱቤን በስልክዎ ላይ ቀላል ማስታወሻ ያድርጉ።',
  introSlide2Title: 'ገንዘብዎን ፈጣን ይመልከቱ',
  introSlide2Body: 'የዛሬ ሁኔታዎን በጥቂት ሰከንዶች ይረዱ።',
  introSlide3Title: 'ሶስት ቁልፎች ብቻ',
  introSlide3Body: 'ሸጥ፣ ወጪ እና ዱቤ በፍጥነት ለመመዝገብ ይጠቀሙ።',
  introLetsStart: 'እንጀምር',
  introNext: 'ቀጣይ →',
  introSkip: 'ዝለል',

  noEntriesPrompt: 'የመጀመሪያ ሽያጭዎን ለማስቀመጥ ከላይ ያለውን ቁልፍ ይጫኑ',

  saleSaved: 'ሽያጭ ተቀምጧል',
  expenseSaved: 'ወጪ ተቀምጧል',
  creditSaved: 'ዱቤ ተቀምጧል',
  undone: 'ተመልሷል',

  statusOverdue: 'ዘግይቷል',
  statusDueSoon: 'ይቅረባል',
  statusOk: 'ጥሩ',

  periodDay: 'ቀን',
  periodWeek: 'ሳምንት',
  periodMonth: 'ወር',
  totalSales: 'ጠቅላላ ሽያጭ',
  totalExpenses: 'ጠቅላላ ወጪ',
  topProductsWeek: 'የሳምንቱ ምርጥ ሽያጭ',
  topProductsMonth: 'የወሩ ምርጥ ሽያጭ',
  topProductsDay: 'ዛሬ ምርጥ ሽያጭ',
  byQuantity: 'በብዛት',
  byRevenue: 'በገቢ',
  weekBreakdown: 'በቀን',
  monthBreakdown: 'በሳምንት',
  weekOf: 'ሳምንት',
  noSalesThisPeriod: 'በዚህ ወቅት ሽያጭ የለም',
  week: 'ሳምንት',

  typeSale: 'በጽሑፍ ሽያጭ',
  typeSaleLabel: 'በጽሑፍ ሽያጭ',
};

const EN_OVERRIDES = {
  appName: 'Gebya',
  appearance: 'Appearance',
  appearanceHint: 'Choose the look that feels easiest on your eyes.',
  lightMode: 'Light',
  darkMode: 'Dark',
  today: 'Today',
  todayLabel: 'Today',
  credit: 'Dubie',
  creditLabel: 'Dubie',
  iSold: 'Type Sale',
  iSoldLabel: 'Type Sale',
  iSpent: 'I Spent',
  iSpentLabel: 'I Spent',
  creditBtn: 'Dubie',
  creditBtnLabel: 'Dubie',
  todaysEntries: "Today's Entries",
  onboardTagline: 'Your shop notebook',
  onboardWelcome: 'Start your notebook',
  onboardSubtitle: 'Your business notebook',
  onboardDesc: 'Enter your name and start using Gebya right away.',
  onboardPromiseSimple: 'Simple notebook for sales, spending, and Dubie',
  onboardPromiseFast: 'Start with your name only',
  onboardPromisePrivate: 'Your records stay on this phone',
  onboardGetStarted: 'Start using Gebya',
  trustCardTitle: 'Your notebook stays on this phone',
  trustCardBody: 'Save your sales, close the app, and open again later. Your records stay here on this phone.',
  trustCardAction: 'Record your first sale',
  trustLastSaved: 'Last saved',
  trustTodayCount: 'saved today',
  trustReopenHint: 'Close and reopen anytime. Your records stay here.',
  offlineReadyTitle: 'Offline mode is ready',
  offlineReadyBody: 'Gebya can reopen even with weak connection, and your saved notebook stays on this phone.',
  typeSale: 'Type Sale',
  typeSaleLabel: 'Type Sale',

  // OfflineStatusStrip
  offlineLabel: 'Offline',
  offlineDetail: 'saves on this phone',
  telegramWaiting: 'Telegram waiting',
  telegramRetry: 'Retry',
  updateReady: 'Update ready',
  updateTapRefresh: 'tap to refresh',
  updateButton: 'Update',
  offlineReadyStatus: 'Offline ready',
  offlineReadyDetail: 'works without internet',
  syncConflict: 'Sync conflict',

  // TxRow
  txCredit: 'credit',
  txEdit: 'Edit',
  txDelete: 'Delete',
  txViewPhoto: 'View transaction photo',
  txShowItems: 'Show items',
  txMore: 'More',
  txUnaccounted: 'Unaccounted',
  txExcess: 'Excess',

  // Handler toasts
  toastCustomerUpdated: 'Customer updated',
  toastEntryUpdated: 'Entry updated',
  toastEntryUpdateFailed: 'Could not update entry',
  toastReverseFailed: 'Could not reverse entry',
  toastEntryReversed: 'Entry reversed',

  // Greeting
  greetingMorning: "Good morning — start tracking today's sales",
  greetingAfternoon: 'Keep going — record your sales as you sell',
  greetingEvening: "Don't forget today's last sales",

  // Backup nudge
  backupTitle: 'Back up your notebook',
  backupTitleStale: 'Backup is overdue',
  backupBody: "Your data lives only on this phone. Back it up so a lost phone doesn't mean lost records.",
  backupAction: 'Back up',
  backupLater: 'Later',

  // Today entries
  entriesHeader: 'ENTRIES',
  entriesShare: 'Share',
  entriesEmpty: 'No entries yet',
  entriesEmptyHint: 'Tap above to start',

  // Credit tab
  customersLabel: 'Customers',
  suppliersLabel: 'Suppliers',

  // Action bar
  saleButton: 'Sale',
  itemsButton: 'Items',
  expenseButton: 'Expense',
  creditButton: 'Credit',

  // Credit detail
  addCustomer: '+ Add Customer',
  addSupplier: '+ Add Supplier',
  creditGave: 'YOU GAVE (Dubie)',
  creditGot: 'YOU GOT (Paid)',

  // Save/update error toasts
  saveFailed: 'Could not save. Please try again.',
  updateFailed: 'Could not update. Please try again.',
  addItem: 'Add Item',
  tapAddItemToConfirm: 'Tap Add Item to confirm',

  // Customer archive
  archiveCustomer: 'Archive Customer',
  restoreCustomer: 'Restore Customer',
  archiveConfirm: 'Archive {name}?',
  archiveBalanceWarning: 'This customer has {balance} birr outstanding. Archived records are preserved for history.',

  // Promise tracking
  recordPromise: 'Record Promise',
  promisedPayDate: 'Promised to pay by {date}',
  missedPromise: 'Missed promise — was due {date}',
  promiseNote: 'Note (optional)',
  promiseSaved: 'Promise recorded',
  promiseCleared: 'Promise cleared',
  clearPromise: 'Clear promise',
  promisePayToday: 'Promised to pay today',
  daysOverdue: '{days}d overdue',
  needAttention: 'Need attention',
  chaseCount: '{count} need attention',
};

const AM_OVERRIDES = {
  // Brand & navigation
  appName: 'ገበያ',
  appearance: 'መልክ',
  appearanceHint: 'ለዓይንዎ ቀላል የሚሆነውን መልክ ይምረጡ።',
  lightMode: 'ብርሃን',
  darkMode: 'ጨለማ',
  loading: 'ማስታወሻዎን በመጫን ላይ…',
  today: 'ዛሬ',
  todayLabel: 'ዛሬ',
  credit: 'ዱቤ',
  creditLabel: 'ዱቤ',
  report: 'ሪፖርት',
  reminders: 'ማስታወሻ',
  settings: 'ቅንብሮች',
  close: 'ዝጋ',
  cancel: 'ሰርዝ',
  add: 'አክል',
  delete: 'ሰርዝ',
  saved: 'ተቀምጧል',
  done: 'ተጠናቀቀ',

  // Install / PWA — NEW (these were missing in v1)
  installSectionTitle: 'መተግበሪያ ጫን',
  installBannerTitle: 'ገበያን በዚህ ስልክ ላይ ጫን',
  installBannerBody: 'ገበያን ወደ መነሻ ገጽ ያስቀምጡት እና እንደ መተግበሪያ ይክፈቱት።',
  installNow: 'አሁን ጫን',
  installHowTo: 'ጫን',
  installGuideButton: 'እንዴት እንደሚጫን',
  installGuideTitle: 'ገበያን በስልክዎ ላይ ጫን',
  installGuideHint: 'አንድ ጊዜ ብቻ ይህን ያድርጉ፣ ከዚያ ገበያን ከመነሻ ገጽ ይክፈቱት።',
  installGuideDeviceTitle: 'የስልክ ጫን እርምጃዎች',
  installAlreadyInstalled: 'አስቀድሞ ተጭኗል',
  installStatusInstalled: 'በመነሻ ገጽ ላይ ተጭኗል',
  installStatusBrowser: 'በብራውዘር ውስጥ እየሰራ ነው',
  installStatusOnline: 'አሁን ኢንተርኔት አለ',
  installStatusOffline: 'አሁን ከኢንተርኔት ውጪ ነው',
  installChecklistOffline: 'ከኢንተርኔት ውጪ የሚሰራ ማስታወሻ',
  installChecklistHomeScreen: 'የመነሻ ገጽ ጫን',
  installChecklistData: 'የውሂብ ቦታ',
  installChecklistReady: 'ዝግጁ',
  installChecklistInstalled: 'ተጭኗል',
  installChecklistPending: 'ገና አይደለም',
  installChecklistOnPhone: 'በዚህ ስልክ',
  installIosStep1: 'ገበያን በ iPhone Safari ውስጥ ይክፈቱት።',
  installIosStep2: 'የማጋራት ቁልፉን ይጫኑ፣ ከዚያ "Add to Home Screen" ይምረጡ።',
  installIosStep3: '"Add" ይጫኑ፣ ከዚያ ገበያን ከመነሻ ገጽ ይክፈቱት።',
  installAndroidStep1: 'ገበያን በ Android Chrome ውስጥ ይክፈቱት።',
  installAndroidStep2: 'የብራውዘር ምናሌ ይክፈቱ፣ ከዚያ "Install app" ወይም "Add to Home screen" ይጫኑ።',
  installAndroidStep3: 'ያረጋግጡ፣ ከዚያ ገበያን ከመነሻ ገጽ ይክፈቱት።',
  installGenericStep1: 'ገበያን በስልክዎ ብራውዘር ይክፈቱት።',
  installGenericStep2: 'የብራውዘር ምናሌ ይክፈቱ እና "Install app" ወይም "Add to Home Screen" ይፈልጉ።',
  installGenericStep3: 'ያስቀምጡት፣ ከዚያ ገበያን ከመነሻ ገጽ ይክፈቱት።',

  // Today screen totals & summary
  sales: 'ሽያጭ',
  spent: 'ወጪ',
  salesLabel: 'ሽያጭ',
  expenses: 'ወጪዎች',
  totalSales: 'ጠቅላላ ሽያጭ',
  totalExpenses: 'ጠቅላላ ወጪ',
  todaysProfit: 'የዛሬ ትርፍ',
  estimatedProfit: 'የተገመተ ትርፍ',
  todaysSales: 'የዛሬ ሽያጭ',
  todaysBreakdown: 'የዛሬ ሂሳብ',
  todaysEntries: 'የዛሬ ግቤቶች',
  netProfit: 'ንጹህ ትርፍ',
  costOfGoods: 'የእቃ ዋጋ',
  profit: 'ትርፍ',
  edited: 'ተስተካክሏል',
  birr: 'ብር',
  birrSaved: 'ብር ተቀምጧል',
  tapToReveal: 'ለማሳየት ይጫኑ',
  tapToRevealAria: 'መጠንን ለማሳየት ይጫኑ',
  hideAmountAria: 'መጠንን ደብቅ',
  totalsHidden: 'ጠቅላላዎቹ ተደብቀዋል — ለማሳየት ይጫኑ',
  totalsVisible: 'ጠቅላላዎቹ ይታያሉ — ለመደበቅ ይጫኑ',
  partialCostDisclaimer: 'አንዳንድ እቃዎች የዋጋ መረጃ ጎድሏቸዋል — ይህ ግምት ከትክክለኛው ትርፍ ያነሰ ሊሆን ይችላል',
  partialCostTip: 'ትክክለኛ ትርፍ ለማየት ለእቃዎቹ የዋጋ ያስገቡ',
  advancedHint: 'ትክክለኛውን ትርፍ ለማየት ሽያጭ ሲመዘግቡ "ተጨማሪ" ይጫኑ',
  weekTrend: 'የ7 ቀን አዝማሚያ',
  thisWeek: 'ይህ ሳምንት',
  topProducts: 'ዛሬ ምርጥ ሽያጭ',
  topProductsWeek: 'የሳምንቱ ምርጥ ሽያጭ',
  topProductsMonth: 'የወሩ ምርጥ ሽያጭ',
  topProductsDay: 'ዛሬ ምርጥ ሽያጭ',
  byQuantity: 'በብዛት',
  byRevenue: 'በገቢ',
  weekBreakdown: 'በቀን',
  monthBreakdown: 'በሳምንት',
  weekOf: 'ሳምንት',
  noSalesThisPeriod: 'በዚህ ወቅት ሽያጭ የለም',
  week: 'ሳምንት',
  byDay: 'በቀን',
  byWeek: 'በሳምንት',
  groupBy: 'ቡድን:',
  revenue: 'ገቢ',
  entries: 'ግቤቶች',

  // Action buttons & types
  iSold: 'ሸጥ',
  iSoldLabel: 'ሸጥ',
  iSpent: 'ወጪ',
  iSpentLabel: 'ወጪ',
  creditBtn: 'ዱቤ',
  creditBtnLabel: 'ዱቤ',
  iSoldSomething: 'ሸጥኩ',
  iSpentSomething: 'ወጪ',
  recordCredit: 'ዱቤ መዝግብ',
  saleSaved: 'ሽያጭ ተቀምጧል',
  expenseSaved: 'ወጪ ተቀምጧል',
  creditSaved: 'ዱቤ ተቀምጧል',
  paymentSaved: 'ክፍያ ተቀምጧል',
  undone: 'ተመልሷል',
  saveSale: 'ሽያጭ አስቀምጥ',
  saveExpense: 'ወጪ አስቀምጥ',
  saveCredit: 'ዱቤ አስቀምጥ',
  addAnotherSale: 'ሌላ ሽያጭ አክል',
  editSale: 'ሽያጭ አርትዕ',
  editExpense: 'ወጪ አርትዕ',
  editCredit: 'ዱቤ አርትዕ',
  editEntry: 'ለማስተካክል',
  editEntryLabel: 'ግቤት አርትዕ',
  editedAt: 'ተስተካክሏል',
  deleteEntry: 'ይህንን ግቤት ይሰርዙ?',
  deleteEntryLabel: 'ግቤት ሰርዝ',
  saving: 'እየተቀመጠ…',

  // Form labels
  whatDidYouSell: 'ምን ሸጡ?',
  sellPlaceholder: 'ዝርዝሩን ይመዝቡ...',
  whatDidYouSpendOn: 'ምን ላይ ወጪ?',
  spendPlaceholder: 'ዝርዝሩን ይመዝቡ...',
  creditNameLabel: 'ስም',
  creditNamePlaceholder: 'ለምሳሌ አበበ…',
  howMuchTotal: 'ጠቅላላ ስንት?',
  howMany: 'ስንት?',
  direction: 'አቅጣጫ',
  theyOweMe: 'ያበደርኩት',
  iOweThem: 'የተበደርኩት',
  owesMe: 'ያበደርኩት',
  iOweLabel: 'የተበደርኩት',
  quickFill: 'ፈጣን ሙላ',
  phoneOptional: 'ስልክ ቁጥር',
  phoneOptionalHint: '(አማራጭ)',
  phonePlaceholder: 'ለምሳሌ 0912345678',
  whenDue: 'መቼ ይከፍላል?',
  pickDate: 'ቀን ምረጥ',
  selectDueDate: 'የመክፍያ ቀን ይምረጡ',
  advancedOptional: 'ተጨማሪ (አማራጭ)',
  whatDidYouPay: 'ለዚህ ምን ከፈሉ?',
  perUnit: '(በአንድ)',
  helpsSeeProfit: 'አማራጭ — ትክክለኛውን ትርፍ ለማየት ይረዳል',
  sellingBelowCost: 'ከዋጋ በታች እየሸጡ ነው። ኪሳራ ሊደርስ ይችላል።',
  sellingBelowCostShort: 'ከዋጋ በታች።',
  profitOnSale: 'በዚህ ሽያጭ ትርፍ:',
  profitLabel: 'ትርፍ:',
  paymentType: 'የክፍያ አይነት',
  cash: 'ጥሬ ገንዘብ',
  bank: 'ባንክ',
  wallet: 'ዋሌት',
  amount: 'መጠን',
  item: 'እቃ',
  quantity: 'ብዛት',
  dueDate: 'የመክፍያ ቀን',
  dueDateOptional: 'የመክፍያ ቀን (አማራጭ)',
  costPriceLabel: 'የዋጋ',
  noteLabel: 'ማስታወሻ',
  paymentNoteOptional: 'የክፍያ ማስታወሻ (አማራጭ)',
  itemNoteOptional: 'የተወሰደው ማስታወሻ (አማራጭ)',
  paymentNotePlaceholder: 'ስለዚህ ክፍያ ማንኛውም ማስታወሻ',
  creditItemPlaceholder: 'የወሰዱት ምንድን ነው',
  pickDateWithEthiopianHint: 'ቀን ይምረጡ፣ እንዲሁም በኢትዮጵያ ቀን መቁጠሪያ እናሳያለን።',
  ethiopianDisplay: 'በኢትዮጵያ ቀን መቁጠሪያ',
  moreOptional: 'ተጨማሪ (አማራጭ)',
  validAmountRequired: 'ትክክለኛ መጠን ያስገቡ',
  creditPhoneHint: '9 አሃዞች፣ ከ7 ወይም 9 ይጀምሩ',
  phoneRequired: 'ስልክ ቁጥር ያስፈልጋል',
  phoneInvalid: '9 አሃዞች በ7 ወይም 9 የሚጀምሩ',

  // Credit / Dubie list
  noCreditRecords: 'የዱቤ መዝገብ የለም',
  addCreditHint: 'ዱቤ ለማክል በዛሬ ገጽ ላይ "ዱቤ" ይጫኑ',
  owedToMe: 'ያበደርኩት',
  iOweAmount: 'የተበደርኩት',
  active: 'ንቁ',
  paid: 'የተከፈለ',
  activeTab: 'ንቁ',
  paidTab: 'የተከፈለ',
  noPaidRecords: 'እስካሁን የተከፈለ መዝገብ የለም',
  allCaughtUp: 'ሁሉም ተከፍሏል!',
  paidInFull: 'ሙሉ በሙሉ ተከፍሏል',
  paidLabel: 'ተከፍሏል',
  due: 'መክፍያ',
  owesMeLabel: 'ያበደርኩት',
  iOweTag: 'የተበደርኩት',
  dueLabelShort: 'መክፍያ',
  backToCredit: 'ወደ ዱቤ ተመለስ',
  originalDebt: 'ዋና ዕዳ',
  amountPaid: 'የተከፈለ',
  stillOwes: 'ቀሪ ዕዳ',
  progress: 'ሂደት',
  percentPaid: '% ተከፍሏል',
  paidSome: 'ከፊል ክፍያ',
  allPaid: 'ሙሉ ተከፍሏል',
  call: 'ደውል',
  recordPartialPayment: 'ከፊል ክፍያ መዝግብ',
  recordPayment: 'ክፍያ መዝግብ',
  markFullyPaid: 'ሙሉ ተከፍሏል ብለህ አድርግ',
  paymentHistory: 'የክፍያ ታሪክ',
  borrowed: 'የተበደረ',
  paidBack: 'የተመለሰ',
  remaining: 'ቀሪ',
  payMethodCash: 'ጥሬ ገንዘብ',
  payMethodBank: 'ባንክ ዝውውር',
  payMethodMobile: 'ሞባይል ገንዘብ',
  paymentExceedsOwed: 'መጠኑ ከሚገባው መጠን ሊበልጥ አይችልም',
  paymentMoreThanBalance: 'ክፍያው ከአሁኑ ቀሪ ሂሳብ ይበልጣል',
  noBalanceToRecordPayment: 'ገና የሚሰበሰብ ቀሪ ሂሳብ የለም',
  balanceAfterEntry: 'ከዚህ ግቤት በኋላ ያለ ቀሪ ሂሳብ',
  savePayment: 'ክፍያ አስቀምጥ',
  currentBalance: 'አሁን ያለ ቀሪ ሂሳብ',
  previousBalance: 'ያለፈው ቀሪ ሂሳብ',
  updatedBalance: 'የተሻሻለ ቀሪ ሂሳብ',
  currentBalanceHint: 'ይህ አዲሱን ዱቤ ካስቀመጡ በኋላ የሚታየው ቀሪ ሂሳብ ነው።',
  remainingBalanceHint: 'ይህ ክፍያውን ካስቀመጡ በኋላ የሚቀረው ቀሪ ሂሳብ ነው።',

  // Status badges
  statusOverdue: 'ዘግይቷል',
  statusDueSoon: 'ይቅረባል',
  statusOk: 'ጥሩ',

  // Periods
  periodDay: 'ቀን',
  periodWeek: 'ሳምንት',
  periodMonth: 'ወር',
  daily: 'ዕለታዊ',
  weekly: 'ሳምንታዊ',
  monthly: 'ወርሃዊ',
  sun: 'እሁድ',
  mon: 'ሰኞ',
  tue: 'ማክሰ',
  wed: 'ረቡዕ',
  thu: 'ሐሙስ',
  fri: 'አርብ',
  sat: 'ቅዳሜ',
  customerSaved: 'ደንበኛ ተቀምጧል',
  customerSaveFailed: 'ደንበኛውን ማስቀመጥ አልተቻለም። እባክዎ ድጋሜ ይሞክሩ።',
  customerHelperText: 'በኋላ የሚያስታውሱትን ማንኛውም መለያ ይጠቀሙ።',
  customerIdentifier: 'የደንበኛ መለያ',
  customerIdentifierPlaceholder: 'ስም፣ ቅጽል፣ ዝምድና፣ ቦታ ወይም ምልክት',
  customerNotePlaceholder: 'ይህንን ደንበኛ ለማስታወስ የሚረዳ ማስታወሻ',
  customerPhoneOptional: 'ስልክ (አማራጭ)',
  customerPhonePlaceholder: 'ስልክ ቁጥር',
  customerTelegramOptional: 'ቴሌግራም (አማራጭ)',
  customerTelegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  customerTotalBalance: 'ጠቅላላ ቀሪ ሂሳብ',
  customerBalance: 'ቀሪ ሂሳብ',
  searchCustomerPlaceholder: 'ደንበኛ ወይም ማስታወሻ ፈልግ…',
  customerSearchHint: 'በስም፣ በማስታወሻ፣ በስልክ ወይም በቴሌግራም ይፈልጉ።',
  customerSearchResults: 'ከ {total} ደንበኞች {shown} ታይተዋል',
  noCustomersFound: 'ምንም ደንበኞች አልተገኙም',
  noCustomersYet: 'ገና ምንም ደንበኞች የሉም',
  noCustomerSearchResults: 'ከዚህ ፍለጋ ጋር የሚዛመዱ ደንበኞች አልተገኙም',
  backToCustomers: 'ወደ ደንበኞች ተመለስ',
  customerTransactionHistory: 'የግብይት ታሪክ',
  paymentRecordedLabel: 'ክፍያ',
  creditAddedLabel: 'ዱቤ ተጨምሯል',
  noTransactionsYet: 'እስካሁን ምንም ግብይት የለም',
  noTransactionsHint: 'ይህንን ታሪክ ለመጀመር ዱቤ ጨምር ወይም ክፍያ መዝግብ ይጠቀሙ።',
  customerNotFound: 'ደንበኛው አልተገኘም',

  // Search & filters
  searchPlaceholder: 'በእቃ ወይም ደንበኛ ፈልግ…',
  noSearchResults: 'ምንም ውጤት',
  noRecords: 'እስካሁን ምንም መዝገብ የለም',
  startRecording: 'ለመጀመር የመጀመሪያ ሽያጭ ወይም ወጪ ይመዝግቡ',
  noEntries: 'ገና ምንም ግቤት የለም። ለመጀመር ከላይ ያሉትን ቁልፎች ይጫኑ።',
  noEntriesPrompt: 'የመጀመሪያ ሽያጭዎን ለማስቀመጥ ከላይ ያለውን ቁልፍ ይጫኑ',

  // Settings
  shopProfile: 'መገለጫ',
  userName: 'ስም',
  phoneNumber: 'ስልክ ቁጥር',
  privacy: 'ግላዊነት',
  hideAmounts: 'ቁጥሮችን ደብቅ',
  paymentMethods: 'የክፍያ ዘዴዎች',
  banks: 'ባንኮች',
  mobileWallets: 'ሞባይል ዋሌት',
  onlyEnabled: 'የነቁ ዘዴዎች ብቻ በቅጹ ውስጥ ይታያሉ',
  recurringExpenses: 'ተደጋጋሚ ወጪዎች',
  recurringHint: 'ብዙ ጊዜ ለሚያስገቡዋቸው ወጪዎች ፈጣን ቅጽ',
  addRecurring: 'ተደጋጋሚ ወጪ አክል',
  demoCardSectionLabel: 'ፈጣን ሙላ (ምሳሌዎች)',
  addRecurringPopupGuide: 'ይህን ወጪ ለሚቀጥሉ ጊዜያት አስቀምጥ',
  addAndUse: 'አስቀምጥ እና ተጠቀም',
  addRecurringHint: 'ሌሎች ተደጋጋሚ ወጪዎችን በቅንብሮች ውስጥ ማከል ይችላሉ',
  frequency: 'ድግግሞሽ',
  expenseName: 'የወጪ ስም (ለምሳሌ ኪራይ)',
  yourData: 'የእርስዎ ውሂብ',
  storedOnDevice: 'በዚህ ስልክ ላይ ተቀምጧል',
  exportCSV: 'CSV ወደ ውጭ ላክ',
  exportHint: 'ስፕሬድሺት ምትኬ ያውርዱ',
  exportFailed: 'ኤክስፖርት አልተሳካም',
  clearAll: 'ሁሉንም ውሂብ አጥፋ',
  clearHint: 'ሁሉም ነገር ሙሉ በሙሉ ይሰረዛል — መጀመሪያ ይልኩ!',
  about: 'ስለ ፕሮግራሙ',
  privacyNote: 'ውሂቡ ከዚህ ስልክ አይወጣም። ምዝገባ አያስፈልግም።',
  worksOffline: 'ከኢንተርኔት ውጪም ይሰራል · ውሂቡ በስልክዎ ላይ ይቆያል · ነፃ',
  achievementBadges: 'የስኬት ባጆች',
  badgesEarned: 'ተገኝቷል',
  noBadges: 'ባጆች ለማግኘት ኢላማዎችን ያሟሉ!',
  clearConfirm: 'ሁሉንም ውሂብ አጥፋ?',
  clearConfirmMsg: 'ይህ ሁሉን {count} ግቤቶችና {credits} የዱቤ መዝገቦችን ሙሉ በሙሉ ይሰርዛል። ሊቀለበስ አይችልም።',
  yesDelete: 'አዎ፣ ሁሉንም ሰርዝ',
  dataCleared: 'ውሂቡ ተሰርዟል',
  reloading: 'እንደገና በመጫን ላይ…',
  saveChanges: 'ለውጦችን አስቀምጥ',
  copiedToClipboard: 'ወደ ቅጂ ተገልብጧል',
  shareMyStats: 'ስታቲስቲክስን አጋራ',
  usageInsights: 'የአጠቃቀም ዝርዝር',
  dayStreak: 'ቀን ተከታታይ',
  best: 'ምርጥ',
  daysActive: 'ንቁ ቀናት',
  since: 'ጀምሮ',
  totalEntries: 'ግቤቶች',
  sessions: 'ክፍለ ጊዜ',
  newBestDay: 'አዲስ ምርጥ ቀን',

  // Share
  shareReport: 'ሪፖርት አጋራ',
  shareReportBtn: 'ዛሬን አጋራ',
  shareTitle: 'ዕለታዊ ሪፖርት አጋራ',
  shareDailyReport: 'ዕለታዊ ሪፖርት',
  shareTopItems: 'ምርጥ ሽያጭ',
  shareSentVia: 'በ ገበያ (Gebya) ተልኳል',
  shareViaDevice: 'በስልክ አጋራ',
  openTelegram: 'ቴሌግራም ክፈት',
  copyText: 'ጽሑፍ ቅዳ',

  // Telegram
  telegramLabel: 'ቴሌግራም / ግንኙነት',
  telegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  connectTelegram: 'ቴሌግራም አገናኝ',
  manageTelegram: 'ቴሌግራም አስተዳድር',
  telegramConnection: 'የቴሌግራም ግንኙነት',
  telegramConnectHint: 'አንድ ጊዜ ቴሌግራም ያገናኙ፣ ከዚያ ሲፈልጉ የቀሪ ሂሳብ ማሳወቂያ ያብሩ።',
  telegramConnectedHint: 'ይህ ደንበኛ በቴሌግራም የቀሪ ሂሳብ መልእክት ሊደርሰው ይችላል።',
  notifyOnTelegram: 'በቴሌግራም አሳውቅ',
  notifyOnTelegramHint: 'ዱቤ ወይም ክፍያ ከተመዘገበ በኋላ ቴሌግራም ራሱን ይከፍታል።',
  telegramNotifyEnabledState: 'ለዚህ ደንበኛ ራስ-ሰር የቴሌግራም መክፈት ነቅቷል።',
  telegramNotifyDisabledState: 'ቴሌግራም አማራጭ ብቻ ነው፣ ራሱን አይከፍትም።',
  telegramNeedContactHint: 'መጀመሪያ የቴሌግራም ስም ወይም ሊንክ ያስገቡ።',
  telegramFormatHint: '@username, t.me/... ወይም https://t.me/... ብቻ ይጠቀሙ።',
  telegramAutoUpdatesTitle: 'ራስ-ሰር የቀሪ ሂሳብ ማሳወቂያ',
  telegramAutoUpdatesBody: 'ከተገናኝ በኋላ የዚህ ደንበኛ ቀሪ ሂሳብ ሲቀየር በቴሌግራም መልእክት ሊደርሰው ይችላል።',
  telegramNotifyConnectFirst: 'ቴሌግራምን በመጀመሪያ ያገናኙ፣ ከዚያ ይህን ያብሩ።',
  telegramConnectFirstToast: 'ዝመና ለመላክ ቴሌግራምን በመጀመሪያ ያገናኙ።',
  qrPrimaryMethod: 'QR ኮድ',
  telegramQrHint: 'ይህንን QR ኮድ እንዲስካን አድርጉት እና የቴሌግራም ግንኙነት ሊንኩን ይክፈት።',
  shareInviteLink: 'የግብዣ ሊንክ አጋራ',
  shareInviteLinkHint: 'ይህንን ሊንክ ቅዳ እና በሚጠቀሙበት ማንኛውም መንገድ ላክ።',
  copyLink: 'ሊንክ ቅዳ',
  inviteLinkCopied: 'የግብዣ ሊንክ ተቀድቷል',
  copyFailed: 'ሊንኩን መቅዳት አልተቻለም',
  manualTelegramFallback: 'በእጅ ማስገባት',
  manualTelegramFallbackHint: 'ካስፈለገ የደንበኛውን @username ወይም t.me ሊንክ በእጅ ያስገቡ።',
  confirmConnection: 'ግንኙነቱን አረጋግጥ',
  skipForNow: 'ለአሁን ዝለል',

  // Provider chips
  payingVia: 'በ',
  addCustomBank: 'ባንክ አክል…',
  addCustomWallet: 'ዋሌት አክል…',
  customProviderName: 'ስም',
  providerEnabled: 'ነቅቷል',
  providerDisabled: 'ተዘግቷል',

  // Onboarding
  onboardWelcome: 'ማስታወሻዎን ጀምር',
  onboardSubtitle: 'የሱቅ ማስታወሻ',
  onboardTagline: 'የሱቅ ማስታወሻ ደብተር',
  onboardDesc: 'ስምዎን ያስገቡና ገበያን ወዲያው ይጀምሩ።',
  onboardNamePlaceholder: 'ለምሳሌ ትግስት',
  onboardPhoneOptional: '(አማራጭ)',
  onboardPhoneHelper: 'ስልክዎን በቅንብሮች ውስጥ በኋላ ማከል ይችላሉ።',
  onboardPromiseSimple: 'ለሽያጭ፣ ወጪ እና ዱቤ ቀላል ማስታወሻ',
  onboardPromiseFast: 'በስምዎ ብቻ ይጀምሩ',
  onboardPromisePrivate: 'መዝገቦችዎ በዚህ ስልክ ላይ ይቆያሉ',
  onboardGetStarted: 'ገበያን ጀምር',
  onboardSettingUp: 'በማዘጋጀት ላይ…',
  onboardFooter: 'መረጃዎ በስልክዎ ላይ ይቆያል · ከባንክ ጋር አልተገናኘም · ነፃ',

  // Trust card
  trustCardTitle: 'ማስታወሻዎ በዚህ ስልክ ላይ ይቆያል',
  trustCardBody: 'ሽያጮችዎን ያስቀምጡ፣ መተግበሪያውን ዝጉ፣ በኋላም እንደገና ይክፈቱ። መዝገቦችዎ በዚህ ስልክ ላይ ይቆያሉ።',
  trustCardAction: 'የመጀመሪያ ሽያጭዎን ያስቀምጡ',
  trustLastSaved: 'የመጨረሻ ጊዜ የተቀመጠ',
  trustTodayCount: 'ዛሬ የተቀመጠ',
  trustReopenHint: 'በማንኛውም ጊዜ ዝጉና እንደገና ይክፈቱ፤ መዝገቦችዎ አይጠፉም።',

  // Offline / online
  offlineReadyTitle: 'የኦፍላይን አጠቃቀም ዝግጁ ነው',
  offlineReadyBody: 'ግንኙነት ቢደክምም ገበያን እንደገና መክፈት ይችላሉ፣ መዝገቦችዎም በዚህ ስልክ ላይ ይቆያሉ።',
  offlineNowTitle: 'አሁን ከኢንተርኔት ውጪ ነዎት',
  offlineNowBody: 'በዚህ ስልክ ላይ የተቀመጠው ማስታወሻ እንደተለመደው ይሰራል።',
  updateReadyTitle: 'አዲስ እትም ዝግጁ ነው',
  updateReadyBody: 'አዲስ የመተግበሪያ እትም አለ። አንድ ጊዜ ያድሱ።',
  refreshApp: 'መተግበሪያውን አድስ',
  notNow: 'አሁን አይደለም',

  tryAgain: 'እንደገና ሞክር',
  typeSale: 'በጽሑፍ ሽያጭ',
  typeSaleLabel: 'በጽሑፍ ሽያጭ',

  // Intro slides
  introSlide1Title: 'የሱቅ ማስታወሻ',
  introSlide1Body: 'ሽያጭ፣ ወጪ እና ዱቤን በስልክዎ ላይ ቀላል ማስታወሻ ያድርጉ።',
  introSlide2Title: 'ገንዘብዎን ፈጣን ይመልከቱ',
  introSlide2Body: 'የዛሬ ሁኔታዎን በጥቂት ሰከንዶች ይረዱ።',
  introSlide3Title: 'ሶስት ቁልፎች ብቻ',
  introSlide3Body: 'ሸጥ፣ ወጪ እና ዱቤ በፍጥነት ለመመዝገብ ይጠቀሙ።',
  introLetsStart: 'እንጀምር',
  introNext: 'ቀጣይ →',
  introSkip: 'ዝለል',

  // OfflineStatusStrip
  offlineLabel: 'ኔትወርክ የለም',
  offlineDetail: 'በዚህ ስልክ ይቀመጣል',
  telegramWaiting: 'ቴሌግራም ይጠብቃል',
  telegramRetry: 'እንደገና',
  updateReady: 'አዲስ ስሪት ዝግጁ ነው',
  updateTapRefresh: 'ለማደስ ይጫኑ',
  updateButton: 'አድስ',
  offlineReadyStatus: 'ከመስመር ውጭ ዝግጁ',
  offlineReadyDetail: 'ያለ ኢንተርኔት ይሰራል',
  syncConflict: 'ሁከት ተፈጠረ',

  // TxRow
  txCredit: 'ዱቤ',
  txEdit: 'አርትዕ',
  txDelete: 'ሰርዝ',
  txViewPhoto: 'የግብይት ፎቶ ይመልከቱ',
  txShowItems: 'እቃዎችን አሳይ',
  txMore: 'ተጨማሪ',
  txUnaccounted: 'ቀሪ',
  txExcess: 'በላይ',

  // Handler toasts
  toastCustomerUpdated: 'ተስተካክሏል',
  toastEntryUpdated: 'ተስተካክሏል',
  toastEntryUpdateFailed: 'ማስተካከል አልተሳካም',
  toastReverseFailed: 'ሰርዝ አልተሳካም',
  toastEntryReversed: 'ተሰርዟል',

  // Greeting
  greetingMorning: '👋 ዛሬ ዕለት — የዛሬ ሽያጮን ይመዝገቡ',
  greetingAfternoon: '📌 ቀጥል — ሽያጮን በሚሸጡበት ጊዜ ይመዝገቡ',
  greetingEvening: '🌙 የዛሬ የመጨረሻ ሽያጮን ያል⟿',

  // Backup nudge
  backupTitle: 'የማስታወሻ ደብተርዎን ያስቀምጡ',
  backupTitleStale: 'ደብተርዎን ለማስቀመጥ ጊዜው አልፏል',
  backupBody: 'የእርስዎ መረጃ የሚገኘው በዚህ ስልክ ላይ ብቻ ነው። ስልክዎ ቢጠፋ መረጃዎ እንዳይጠፋ አሁኑኑ ያስቀምጡት።',
  backupAction: 'ያስቀምጡ',
  backupLater: 'በኋላ',

  // Today entries
  entriesHeader: 'ምዝገባዎች',
  entriesShare: 'አጋራ',
  entriesEmpty: 'ገና ምንም ምዝገባ የለም',
  entriesEmptyHint: 'ለመጀመር ከላይ ይጫኑ',

  // Credit tab
  customersLabel: 'ደንበኞች',
  suppliersLabel: 'አቅራቢዎች',

  // Action bar
  saleButton: 'ሽያጭ',
  itemsButton: 'አtems',
  expenseButton: 'ወጪ',
  creditButton: 'ዱቤ',

  // Credit detail
  addSupplier: 'አቅራቢ ጨምር',
  creditGave: 'እቃ በዱቤ ሰጠሁ (-)',
  creditGot: 'ክፍያ ተቀበልኩ (+)',

  // Save/update error toasts
  saveFailed: 'ማስቀመጥ አልተሳካም — እንደገና ይሞክሩ',
  updateFailed: 'ማስተካከል አልተሳካም — እንደገና ይሞክሩ',
  addItem: 'አክል',
  tapAddItemToConfirm: 'ለማስቀመጥ አክል ይጫኑ',

  // Customer archive
  archiveCustomer: 'ደንበኛን አርክስ',
  restoreCustomer: 'ደንበኛን መልስ',
  archiveConfirm: '{name} አርክስ?',
  archiveBalanceWarning: 'ይህ ደንበኛ {balance} ብር ዕዳ አለበት። የአርክስ መዝገቦች ለታሪክ ይቀመጣሉ።',

  // Promise tracking
  recordPromise: 'የተስፋፉበትን ቀን ይመዝግቡ',
  promisedPayDate: 'እስከ {date} ይከፍላል ብሏል',
  missedPromise: 'የጠበቀው ቀን አልፏል — {date} ነበር',
  promiseNote: 'ማስታወሻ (አማራጭ)',
  promiseSaved: 'የተስፋፉበት ተመዝግቧል',
  promiseCleared: 'የተስፋፉበት ተወግዷል',
  clearPromise: 'አስወግድ',
  promisePayToday: 'ዛሬ ይከፍላል ብሏል',
  daysOverdue: '{days} ቀን ያለፈው',
  needAttention: 'ትኩረት የሚሹ',
  chaseCount: '{count} ትኩረት ይፈልጋሉ',
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  // Default to Amharic for new users (most Gebya shopkeepers are Amharic-first).
  // Existing users who've toggled keep their saved choice via localStorage.
  const [lang, setLang] = useState(() => localStorage.getItem('gebya_lang') || 'am');

  useEffect(() => {
    document.documentElement.lang = lang;
    document.body.dataset.lang = lang;
    localStorage.setItem('gebya_lang', lang);
  }, [lang]);

  const toggleLang = () => {
    setLang(prev => {
      const next = prev === 'en' ? 'am' : 'en';
      return next;
    });
  };

  const t = lang === 'am' ? { ...AM, ...AM_OVERRIDES } : { ...EN, ...EN_OVERRIDES };

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}



