// AUTO-GENERATED. Two layers:
//  BOOTSTRAP_FILES  - migration SQL (idempotent) to CREATE missing tables.
//  BOOTSTRAP_ALTERS - one ADD COLUMN IF NOT EXISTS per column in the live
//    drizzle schema (@workspace/db/schema) to CONVERGE any existing table
//    whose columns drifted from the code. ensureSchema runs both at request
//    time, where DATABASE_URL + network are available.
export const BOOTSTRAP_FILES: string[] = [
  "CREATE TABLE IF NOT EXISTS \"transactions\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"local_id\" bigint,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"transaction_id\" varchar(128) NOT NULL,\n\t\"type\" varchar(32) NOT NULL,\n\t\"amount\" real DEFAULT 0 NOT NULL,\n\t\"item_name\" text NOT NULL,\n\t\"cost_price\" real,\n\t\"quantity\" integer DEFAULT 1 NOT NULL,\n\t\"profit\" real,\n\t\"is_credit\" boolean DEFAULT false,\n\t\"customer_id\" integer,\n\t\"customer_name\" text,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"ethiopian_date\" text,\n\t\"payment_type\" varchar(64),\n\t\"payment_provider\" varchar(64),\n\t\"sale_settlement_mode\" varchar(32),\n\t\"paid_amount\" real,\n\t\"remaining_amount\" real,\n\t\"settlement_due_date\" bigint,\n\t\"source\" varchar(32),\n\t\"was_edited\" boolean DEFAULT false,\n\t\"actor_role\" varchar(32),\n\t\"actor_staff_member_id\" integer,\n\t\"actor_name_snapshot\" text,\n\t\"deleted_at\" bigint,\n\t\"business_id\" integer NOT NULL,\n\t\"schema_version\" integer DEFAULT 1,\n\t\"sync_version\" integer DEFAULT 1,\n\t\"synced_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"transactions_device_local\" UNIQUE(\"device_id\",\"local_id\"),\n\tCONSTRAINT \"transactions_device_txn\" UNIQUE(\"device_id\",\"transaction_id\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"customers\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"local_id\" bigint,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"transaction_id\" varchar(128) NOT NULL,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"name\" text NOT NULL,\n\t\"email\" text,\n\t\"address\" text,\n\t\"active\" boolean DEFAULT true,\n\t\"total_purchases\" integer DEFAULT 0,\n\t\"last_purchase_at\" bigint,\n\t\"note\" text,\n\t\"telegram_chat_id\" text,\n\t\"telegram_link_requested_at\" bigint,\n\t\"display_name\" text,\n\t\"phone_number\" text,\n\t\"telegram_username\" text,\n\t\"telegram_notify_enabled\" boolean DEFAULT false,\n\t\"telegram_link_token\" text,\n\t\"telegram_linked_at\" bigint,\n\t\"business_id\" integer NOT NULL,\n\t\"schema_version\" integer DEFAULT 1,\n\t\"sync_version\" integer DEFAULT 1,\n\t\"synced_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"customers_device_local\" UNIQUE(\"device_id\",\"local_id\"),\n\tCONSTRAINT \"customers_device_txn\" UNIQUE(\"device_id\",\"transaction_id\"),\n\tCONSTRAINT \"customers_phone_format\" CHECK (\"customers\".\"phone_number\" IS NULL OR \"customers\".\"phone_number\" ~ '^\\+251[79]\\d{8}$')\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"customer_transactions\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"local_id\" bigint,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"transaction_id\" varchar(128) NOT NULL,\n\t\"customer_id\" integer NOT NULL,\n\t\"amount\" real DEFAULT 0 NOT NULL,\n\t\"type\" varchar(32) DEFAULT 'payment' NOT NULL,\n\t\"note\" text,\n\t\"item_note\" text,\n\t\"due_date\" bigint,\n\t\"reference_code\" text,\n\t\"telegram_delivery_state\" varchar(32),\n\t\"telegram_delivery_error\" text,\n\t\"telegram_delivery_attempted_at\" bigint,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"business_id\" integer NOT NULL,\n\t\"schema_version\" integer DEFAULT 1,\n\t\"sync_version\" integer DEFAULT 1,\n\t\"synced_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"cust_txn_device_local\" UNIQUE(\"device_id\",\"local_id\"),\n\tCONSTRAINT \"cust_txn_device_txn\" UNIQUE(\"device_id\",\"transaction_id\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"catalog_entries\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"local_id\" bigint,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"transaction_id\" varchar(128) NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"kind\" varchar(32) DEFAULT 'item' NOT NULL,\n\t\"active\" boolean DEFAULT true,\n\t\"default_price\" real,\n\t\"default_cost\" real,\n\t\"note\" text,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"business_id\" integer NOT NULL,\n\t\"schema_version\" integer DEFAULT 1,\n\t\"sync_version\" integer DEFAULT 1,\n\t\"synced_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"catalog_device_local\" UNIQUE(\"device_id\",\"local_id\"),\n\tCONSTRAINT \"catalog_device_txn\" UNIQUE(\"device_id\",\"transaction_id\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"suppliers\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"local_id\" bigint,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"transaction_id\" varchar(128) NOT NULL,\n\t\"display_name\" text NOT NULL,\n\t\"phone_number\" text,\n\t\"note\" text,\n\t\"active\" boolean DEFAULT true,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"deleted_at\" bigint,\n\t\"business_id\" integer NOT NULL,\n\t\"schema_version\" integer DEFAULT 1,\n\t\"sync_version\" integer DEFAULT 1,\n\t\"synced_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"suppliers_device_local\" UNIQUE(\"device_id\",\"local_id\"),\n\tCONSTRAINT \"suppliers_device_txn\" UNIQUE(\"device_id\",\"transaction_id\"),\n\tCONSTRAINT \"suppliers_phone_format\" CHECK (\"suppliers\".\"phone_number\" IS NULL OR \"suppliers\".\"phone_number\" ~ '^\\+251[79]\\d{8}$')\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"supplier_transactions\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"local_id\" bigint,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"transaction_id\" varchar(128) NOT NULL,\n\t\"supplier_id\" integer NOT NULL,\n\t\"amount\" real DEFAULT 0 NOT NULL,\n\t\"type\" varchar(32) DEFAULT 'payment' NOT NULL,\n\t\"note\" text,\n\t\"item_name\" text NOT NULL,\n\t\"item_kind\" varchar(32),\n\t\"quantity\" integer DEFAULT 1 NOT NULL,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"deleted_at\" bigint,\n\t\"business_id\" integer NOT NULL,\n\t\"schema_version\" integer DEFAULT 1,\n\t\"sync_version\" integer DEFAULT 1,\n\t\"synced_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"supp_txn_device_local\" UNIQUE(\"device_id\",\"local_id\"),\n\tCONSTRAINT \"supp_txn_device_txn\" UNIQUE(\"device_id\",\"transaction_id\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"staff_members\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"local_id\" bigint,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"transaction_id\" varchar(128) NOT NULL,\n\t\"display_name\" text NOT NULL,\n\t\"role\" varchar(32) DEFAULT 'staff',\n\t\"active\" boolean DEFAULT true,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"deactivated_at\" bigint,\n\t\"phone_snapshot\" varchar(32),\n\t\"business_id\" integer NOT NULL,\n\t\"schema_version\" integer DEFAULT 1,\n\t\"sync_version\" integer DEFAULT 1,\n\t\"synced_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"staff_device_local\" UNIQUE(\"device_id\",\"local_id\"),\n\tCONSTRAINT \"staff_device_txn\" UNIQUE(\"device_id\",\"transaction_id\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"settings\" (\n\t\"id\" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name \"settings_id_seq\" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"key\" varchar(128) NOT NULL,\n\t\"value\" text,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"business_id\" integer NOT NULL,\n\t\"schema_version\" integer DEFAULT 1,\n\t\"sync_version\" integer DEFAULT 1,\n\t\"synced_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"settings_device_key\" UNIQUE(\"device_id\",\"key\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"analytics\" (\n\t\"id\" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name \"analytics_id_seq\" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"key\" varchar(128) NOT NULL,\n\t\"value\" text,\n\t\"count\" integer DEFAULT 0,\n\t\"last_seen_at\" bigint,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"business_id\" integer NOT NULL,\n\t\"schema_version\" integer DEFAULT 1,\n\t\"sync_version\" integer DEFAULT 1,\n\t\"synced_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"analytics_device_key\" UNIQUE(\"device_id\",\"key\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"devices\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"user_id\" integer NOT NULL,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"token_hash\" varchar(64),\n\t\"shop_id\" integer,\n\t\"staff_id\" integer,\n\t\"name\" text,\n\t\"status\" varchar(32) DEFAULT 'active',\n\t\"last_seen_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"devices_device_id_unique\" UNIQUE(\"device_id\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"users\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"phone_number\" text NOT NULL,\n\t\"active\" boolean DEFAULT true,\n\t\"preferred_lang\" varchar(8) DEFAULT 'am',\n\t\"telegram_chat_id\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"users_phone_number_unique\" UNIQUE(\"phone_number\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"otps\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"phone_number\" text NOT NULL,\n\t\"code_hash\" text NOT NULL,\n\t\"attempts\" integer DEFAULT 0,\n\t\"max_attempts\" integer DEFAULT 5,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"consumed\" boolean DEFAULT false,\n\t\"created_at\" timestamp with time zone DEFAULT now()\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"snapshots\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"user_id\" integer NOT NULL,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"name\" varchar(256) NOT NULL,\n\t\"description\" text,\n\t\"size_bytes\" integer,\n\t\"tables\" text NOT NULL,\n\t\"record_count\" integer DEFAULT 0,\n\t\"checksum\" varchar(64),\n\t\"payload\" text,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"businesses\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"owner_user_id\" integer NOT NULL,\n\t\"name\" text DEFAULT 'My Shop' NOT NULL,\n\t\"slug\" varchar(64),\n\t\"preferred_lang\" varchar(8) DEFAULT 'am',\n\t\"phone_required\" boolean DEFAULT false,\n\t\"approval_required\" boolean DEFAULT false,\n\t\"created_at\" timestamp with time zone DEFAULT now(),\n\t\"updated_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"businesses_slug_unique\" UNIQUE(\"slug\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"business_members\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"user_id\" integer NOT NULL,\n\t\"display_name\" text,\n\t\"role\" varchar(32) DEFAULT 'cashier' NOT NULL,\n\t\"permissions\" jsonb,\n\t\"invited_by_user_id\" integer,\n\t\"joined_at\" timestamp with time zone,\n\t\"active\" boolean DEFAULT true NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"biz_members_user_business_unique\" UNIQUE(\"user_id\",\"business_id\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"invites\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"invited_by_user_id\" integer NOT NULL,\n\t\"phone_number\" text NOT NULL,\n\t\"staff_name\" text,\n\t\"role\" varchar(32) DEFAULT 'cashier' NOT NULL,\n\t\"token\" varchar(128) NOT NULL,\n\t\"notification_sent\" boolean DEFAULT false,\n\t\"notification_method\" varchar(32),\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"accepted_at\" timestamp with time zone,\n\t\"declined_at\" timestamp with time zone,\n\t\"revoked_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"invites_token_unique\" UNIQUE(\"token\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"audit_log\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"actor_staff_member_id\" integer,\n\t\"actor_device_id\" varchar(128),\n\t\"action\" varchar(64) NOT NULL,\n\t\"entity_type\" varchar(64),\n\t\"entity_id\" varchar(128),\n\t\"blocked_permission\" varchar(64),\n\t\"details\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now()\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"notifications\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"owner_user_id\" integer NOT NULL,\n\t\"type\" varchar(64) NOT NULL,\n\t\"title\" varchar(255) NOT NULL,\n\t\"body\" text NOT NULL,\n\t\"entity_type\" varchar(64),\n\t\"entity_id\" varchar(128),\n\t\"actor_name\" varchar(128),\n\t\"amount\" numeric(12, 2),\n\t\"read\" boolean DEFAULT false NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now()\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"push_subscriptions\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"user_id\" integer NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"endpoint\" text NOT NULL,\n\t\"p256dh\" text NOT NULL,\n\t\"auth\" text NOT NULL,\n\t\"user_agent\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now()\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"staff_events\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"user_id\" integer NOT NULL,\n\t\"client_event_id\" varchar(128) NOT NULL,\n\t\"record_id\" varchar(128),\n\t\"actor_name_snapshot\" text,\n\t\"actor_role_at_event\" varchar(32),\n\t\"event_type\" varchar(32) NOT NULL,\n\t\"occurred_at_device\" timestamp with time zone NOT NULL,\n\t\"payload\" jsonb,\n\t\"created_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"staff_events_client_idempotency\" UNIQUE(\"business_id\",\"client_event_id\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"staff_tasks\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"staff_id\" integer NOT NULL,\n\t\"title\" varchar(255) NOT NULL,\n\t\"description\" text,\n\t\"priority\" varchar(20) DEFAULT 'medium' NOT NULL,\n\t\"status\" varchar(20) DEFAULT 'pending' NOT NULL,\n\t\"due_date\" timestamp with time zone,\n\t\"completed_at\" timestamp with time zone,\n\t\"created_by\" integer NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now(),\n\t\"updated_at\" timestamp with time zone DEFAULT now()\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"staff_attendance\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"staff_id\" integer NOT NULL,\n\t\"clock_in\" timestamp with time zone NOT NULL,\n\t\"clock_out\" timestamp with time zone,\n\t\"notes\" varchar(500),\n\t\"created_at\" timestamp with time zone DEFAULT now()\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"bank_data_shares\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"bank_name\" varchar(128) NOT NULL,\n\t\"bank_user_id\" integer,\n\t\"share_sales_data\" boolean DEFAULT true,\n\t\"share_credit_data\" boolean DEFAULT true,\n\t\"share_customer_data\" boolean DEFAULT false,\n\t\"status\" varchar(32) DEFAULT 'active',\n\t\"consent_given_at\" timestamp with time zone DEFAULT now(),\n\t\"consent_revoked_at\" timestamp with time zone,\n\t\"expires_at\" timestamp with time zone,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now(),\n\t\"updated_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"bank_data_shares_business_bank\" UNIQUE(\"business_id\",\"bank_name\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"bank_report_snapshots\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"bank_data_share_id\" integer,\n\t\"report_version\" integer DEFAULT 1,\n\t\"payload\" jsonb NOT NULL,\n\t\"generated_at\" timestamp with time zone DEFAULT now(),\n\t\"expires_at\" timestamp with time zone\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"bank_users\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"phone_number\" text NOT NULL,\n\t\"display_name\" text,\n\t\"bank_name\" varchar(128) NOT NULL,\n\t\"bank_role\" varchar(32) DEFAULT 'officer',\n\t\"active\" boolean DEFAULT true,\n\t\"created_at\" timestamp with time zone DEFAULT now(),\n\tCONSTRAINT \"bank_users_phone_number_unique\" UNIQUE(\"phone_number\")\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS \"settlements\" (\n\t\"id\" bigint PRIMARY KEY NOT NULL,\n\t\"local_id\" bigint,\n\t\"device_id\" varchar(128) NOT NULL,\n\t\"settlement_id\" varchar(128) NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"staff_id\" integer NOT NULL,\n\t\"period_start\" bigint NOT NULL,\n\t\"period_end\" bigint NOT NULL,\n\t\"expected_cash\" integer DEFAULT 0 NOT NULL,\n\t\"actual_cash\" integer DEFAULT 0 NOT NULL,\n\t\"cash_variance\" integer DEFAULT 0 NOT NULL,\n\t\"expected_transfer\" integer DEFAULT 0 NOT NULL,\n\t\"actual_transfer\" integer DEFAULT 0 NOT NULL,\n\t\"transfer_variance\" integer DEFAULT 0 NOT NULL,\n\t\"expected_total\" integer DEFAULT 0 NOT NULL,\n\t\"actual_total\" integer DEFAULT 0 NOT NULL,\n\t\"total_variance\" integer DEFAULT 0 NOT NULL,\n\t\"adjustments\" jsonb DEFAULT '[]'::jsonb,\n\t\"final_expected_cash\" integer DEFAULT 0 NOT NULL,\n\t\"final_expected_total\" integer DEFAULT 0 NOT NULL,\n\t\"final_variance\" integer DEFAULT 0 NOT NULL,\n\t\"status\" varchar(20) DEFAULT 'checked' NOT NULL,\n\t\"notes\" varchar(500),\n\t\"settled_at\" bigint NOT NULL,\n\t\"settled_by\" integer NOT NULL,\n\t\"reconciled_at\" bigint,\n\t\"reconciled_by\" integer,\n\t\"reconciliation_note\" varchar(500),\n\t\"reconciliation_status\" varchar(32) DEFAULT 'checked' NOT NULL,\n\t\"staff_reported_cash\" integer,\n\t\"staff_reported_transfer\" integer,\n\t\"staff_submitted_at\" bigint,\n\t\"staff_note\" varchar(500),\n\t\"owner_confirmed_cash\" integer,\n\t\"owner_confirmed_transfer\" integer,\n\t\"owner_note\" varchar(500),\n\t\"reconciliation_log\" jsonb DEFAULT '[]'::jsonb,\n\t\"carry_forward\" integer,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint,\n\t\"sync_version\" integer DEFAULT 1 NOT NULL,\n\t\"schema_version\" integer DEFAULT 1 NOT NULL\n);\n--> statement-breakpoint\nALTER TABLE \"transactions\" ADD CONSTRAINT \"transactions_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"customers\" ADD CONSTRAINT \"customers_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"customer_transactions\" ADD CONSTRAINT \"customer_transactions_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"catalog_entries\" ADD CONSTRAINT \"catalog_entries_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"suppliers\" ADD CONSTRAINT \"suppliers_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"supplier_transactions\" ADD CONSTRAINT \"supplier_transactions_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"staff_members\" ADD CONSTRAINT \"staff_members_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"settings\" ADD CONSTRAINT \"settings_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"analytics\" ADD CONSTRAINT \"analytics_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"businesses\" ADD CONSTRAINT \"businesses_owner_user_id_users_id_fk\" FOREIGN KEY (\"owner_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE no action ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"business_members\" ADD CONSTRAINT \"business_members_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"business_members\" ADD CONSTRAINT \"business_members_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"business_members\" ADD CONSTRAINT \"business_members_invited_by_user_id_users_id_fk\" FOREIGN KEY (\"invited_by_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"invites\" ADD CONSTRAINT \"invites_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"invites\" ADD CONSTRAINT \"invites_invited_by_user_id_users_id_fk\" FOREIGN KEY (\"invited_by_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"notifications\" ADD CONSTRAINT \"notifications_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"notifications\" ADD CONSTRAINT \"notifications_owner_user_id_users_id_fk\" FOREIGN KEY (\"owner_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"push_subscriptions\" ADD CONSTRAINT \"push_subscriptions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"push_subscriptions\" ADD CONSTRAINT \"push_subscriptions_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"staff_events\" ADD CONSTRAINT \"staff_events_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"staff_tasks\" ADD CONSTRAINT \"staff_tasks_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"staff_attendance\" ADD CONSTRAINT \"staff_attendance_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"bank_data_shares\" ADD CONSTRAINT \"bank_data_shares_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"bank_data_shares\" ADD CONSTRAINT \"bank_data_shares_bank_user_id_bank_users_id_fk\" FOREIGN KEY (\"bank_user_id\") REFERENCES \"public\".\"bank_users\"(\"id\") ON DELETE set null ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"bank_report_snapshots\" ADD CONSTRAINT \"bank_report_snapshots_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE \"bank_report_snapshots\" ADD CONSTRAINT \"bank_report_snapshots_bank_data_share_id_bank_data_shares_id_fk\" FOREIGN KEY (\"bank_data_share_id\") REFERENCES \"public\".\"bank_data_shares\"(\"id\") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"transactions_business_idx\" ON \"transactions\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"customers_business_idx\" ON \"customers\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"customer_transactions_business_idx\" ON \"customer_transactions\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"catalog_entries_business_idx\" ON \"catalog_entries\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"suppliers_business_idx\" ON \"suppliers\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"supplier_transactions_business_idx\" ON \"supplier_transactions\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"staff_members_business_idx\" ON \"staff_members\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"settings_business_idx\" ON \"settings\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"analytics_business_idx\" ON \"analytics\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"devices_user_idx\" ON \"devices\" USING btree (\"user_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"snapshots_user_idx\" ON \"snapshots\" USING btree (\"user_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"snapshots_device_idx\" ON \"snapshots\" USING btree (\"device_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"businesses_owner_idx\" ON \"businesses\" USING btree (\"owner_user_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"biz_members_business_idx\" ON \"business_members\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"invites_business_idx\" ON \"invites\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"invites_token_idx\" ON \"invites\" USING btree (\"token\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"invites_phone_idx\" ON \"invites\" USING btree (\"phone_number\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"audit_log_business_idx\" ON \"audit_log\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"audit_log_created_idx\" ON \"audit_log\" USING btree (\"created_at\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"audit_log_entity_idx\" ON \"audit_log\" USING btree (\"entity_type\",\"entity_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"notif_biz_owner_idx\" ON \"notifications\" USING btree (\"business_id\",\"owner_user_id\",\"created_at\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"notif_unread_idx\" ON \"notifications\" USING btree (\"business_id\",\"owner_user_id\",\"read\");--> statement-breakpoint\nCREATE UNIQUE INDEX IF NOT EXISTS \"push_sub_endpoint_idx\" ON \"push_subscriptions\" USING btree (\"endpoint\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"push_sub_user_idx\" ON \"push_subscriptions\" USING btree (\"user_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"push_sub_biz_idx\" ON \"push_subscriptions\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"staff_events_business_idx\" ON \"staff_events\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"staff_events_created_idx\" ON \"staff_events\" USING btree (\"created_at\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"staff_tasks_business_idx\" ON \"staff_tasks\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"staff_tasks_staff_idx\" ON \"staff_tasks\" USING btree (\"staff_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"staff_tasks_status_idx\" ON \"staff_tasks\" USING btree (\"status\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"staff_attendance_business_idx\" ON \"staff_attendance\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"staff_attendance_staff_idx\" ON \"staff_attendance\" USING btree (\"staff_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"staff_attendance_clock_in_idx\" ON \"staff_attendance\" USING btree (\"clock_in\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"bank_data_shares_business_idx\" ON \"bank_data_shares\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"bank_data_shares_bank_idx\" ON \"bank_data_shares\" USING btree (\"bank_name\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"bank_report_snapshots_business_idx\" ON \"bank_report_snapshots\" USING btree (\"business_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"bank_report_snapshots_share_idx\" ON \"bank_report_snapshots\" USING btree (\"bank_data_share_id\");--> statement-breakpoint\nCREATE INDEX IF NOT EXISTS \"bank_users_bank_idx\" ON \"bank_users\" USING btree (\"bank_name\");",
  "ALTER TABLE \"businesses\" ADD COLUMN \"phone_required\" boolean DEFAULT false NOT NULL;--> statement-breakpoint\nALTER TABLE \"businesses\" ADD COLUMN \"approval_required\" boolean DEFAULT false NOT NULL;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN \"year\" varchar(16);--> statement-breakpoint\nALTER TABLE \"customer_transactions\" ADD COLUMN \"category_code\" varchar(64);--> statement-breakpoint\nALTER TABLE \"customer_transactions\" ADD COLUMN \"label_code\" varchar(64);\n",
  "ALTER TABLE \"transactions\" ADD COLUMN \"label_code\" varchar(64);",
  "-- Gebya platform-admin toolkit migration\n-- Support tickets + messages, admin shop logs, owner Telegram link token.\n-- Cleaned for the Supabase SQL editor (no drizzle breakpoint comments; idempotent).\n\nCREATE TABLE IF NOT EXISTS \"support_tickets\" (\n  \"id\" serial PRIMARY KEY NOT NULL,\n  \"business_id\" integer NOT NULL,\n  \"owner_user_id\" integer NOT NULL,\n  \"subject\" varchar(255) NOT NULL,\n  \"description\" text NOT NULL,\n  \"status\" varchar(32) DEFAULT 'open' NOT NULL,\n  \"priority\" varchar(16) DEFAULT 'normal' NOT NULL,\n  \"created_at\" timestamptz DEFAULT now(),\n  \"updated_at\" timestamptz DEFAULT now(),\n  \"resolved_at\" timestamptz,\n  \"resolved_by_user_id\" integer\n);\n\nCREATE TABLE IF NOT EXISTS \"support_messages\" (\n  \"id\" serial PRIMARY KEY NOT NULL,\n  \"ticket_id\" integer NOT NULL,\n  \"sender_user_id\" integer NOT NULL,\n  \"sender_role\" varchar(32) NOT NULL,\n  \"body\" text NOT NULL,\n  \"created_at\" timestamptz DEFAULT now()\n);\n\nCREATE TABLE IF NOT EXISTS \"admin_shop_logs\" (\n  \"id\" serial PRIMARY KEY NOT NULL,\n  \"business_id\" integer NOT NULL,\n  \"admin_phone\" varchar(32),\n  \"type\" varchar(32) NOT NULL,\n  \"channel\" varchar(32),\n  \"title\" varchar(200),\n  \"body\" text,\n  \"status\" varchar(32),\n  \"created_at\" timestamp DEFAULT now() NOT NULL\n);\n\nALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"telegram_link_token\" text;\n\nCREATE INDEX IF NOT EXISTS \"support_tickets_business_idx\" ON \"support_tickets\" USING btree (\"business_id\");\nCREATE INDEX IF NOT EXISTS \"support_tickets_status_idx\" ON \"support_tickets\" USING btree (\"status\");\nCREATE INDEX IF NOT EXISTS \"support_messages_ticket_idx\" ON \"support_messages\" USING btree (\"ticket_id\");\nCREATE INDEX IF NOT EXISTS \"admin_shop_logs_business_idx\" ON \"admin_shop_logs\" USING btree (\"business_id\");\n\nDO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'support_messages_ticket_id_support_tickets_id_fk') THEN\n    ALTER TABLE \"support_messages\" ADD CONSTRAINT \"support_messages_ticket_id_support_tickets_id_fk\"\n      FOREIGN KEY (\"ticket_id\") REFERENCES \"public\".\"support_tickets\"(\"id\") ON DELETE cascade ON UPDATE no action;\n  END IF;\nEND $$;\n\nDO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'support_tickets_business_id_businesses_id_fk') THEN\n    ALTER TABLE \"support_tickets\" ADD CONSTRAINT \"support_tickets_business_id_businesses_id_fk\"\n      FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;\n  END IF;\nEND $$;\n\nDO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'support_tickets_owner_user_id_users_id_fk') THEN\n    ALTER TABLE \"support_tickets\" ADD CONSTRAINT \"support_tickets_owner_user_id_users_id_fk\"\n      FOREIGN KEY (\"owner_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;\n  END IF;\nEND $$;\n\nDO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'admin_shop_logs_business_id_businesses_id_fk') THEN\n    ALTER TABLE \"admin_shop_logs\" ADD CONSTRAINT \"admin_shop_logs_business_id_businesses_id_fk\"\n      FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;\n  END IF;\nEND $$;\n",
  "-- Phase 2: Premium tier gating for automated reminders\n-- Adds a `plan` column to businesses to distinguish free vs premium shops.\n-- Automated (cron-triggered) reminders are gated behind plan = 'premium'.\n-- On-demand (manual) reminders work for all plans.\n\nALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"plan\" varchar(32) NOT NULL DEFAULT 'free';\n",
  "-- Gebya platform-admin team members (dynamic allowlist).\n-- The server also auto-creates this table on boot via ensureSchema; this file\n-- is provided for manual application (e.g., Supabase SQL editor) if needed.\n-- Clean and idempotent.\n\nCREATE TABLE IF NOT EXISTS \"platform_admin_members\" (\n  \"id\" serial PRIMARY KEY NOT NULL,\n  \"phone\" text,\n  \"email\" text,\n  \"addedByPhone\" text,\n  \"note\" text,\n  \"createdAt\" timestamptz DEFAULT now() NOT NULL\n);\n\nCREATE UNIQUE INDEX IF NOT EXISTS \"platform_admin_members_phone_unique\" ON \"platform_admin_members\" USING btree (\"phone\");",
  "-- Run this in Supabase SQL Editor\r\n-- Creates the notifications + push_subscriptions tables\r\n-- Safe to run even if other tables don't exist yet\r\n\r\nCREATE TABLE IF NOT EXISTS \"notifications\" (\r\n  \"id\" serial PRIMARY KEY NOT NULL,\r\n  \"business_id\" integer NOT NULL,\r\n  \"owner_user_id\" integer NOT NULL,\r\n  \"type\" varchar(64) NOT NULL,\r\n  \"title\" varchar(255) NOT NULL,\r\n  \"body\" text NOT NULL,\r\n  \"entity_type\" varchar(64),\r\n  \"entity_id\" varchar(128),\r\n  \"actor_name\" varchar(128),\r\n  \"amount\" numeric(12, 2),\r\n  \"read\" boolean DEFAULT false NOT NULL,\r\n  \"created_at\" timestamp with time zone DEFAULT now()\r\n);\r\n\r\nCREATE TABLE IF NOT EXISTS \"push_subscriptions\" (\r\n  \"id\" serial PRIMARY KEY NOT NULL,\r\n  \"user_id\" integer NOT NULL,\r\n  \"business_id\" integer NOT NULL,\r\n  \"endpoint\" text NOT NULL,\r\n  \"p256dh\" text NOT NULL,\r\n  \"auth\" text NOT NULL,\r\n  \"user_agent\" text,\r\n  \"created_at\" timestamp with time zone DEFAULT now()\r\n);\r\n\r\n-- Indexes\r\nCREATE INDEX IF NOT EXISTS \"notif_biz_owner_idx\" ON \"notifications\" USING btree (\"business_id\",\"owner_user_id\",\"created_at\");\r\nCREATE INDEX IF NOT EXISTS \"notif_unread_idx\" ON \"notifications\" USING btree (\"business_id\",\"owner_user_id\",\"read\");\r\nCREATE UNIQUE INDEX IF NOT EXISTS \"push_sub_endpoint_idx\" ON \"push_subscriptions\" USING btree (\"endpoint\");\r\nCREATE INDEX IF NOT EXISTS \"push_sub_user_idx\" ON \"push_subscriptions\" USING btree (\"user_id\");\r\nCREATE INDEX IF NOT EXISTS \"push_sub_biz_idx\" ON \"push_subscriptions\" USING btree (\"business_id\");\r\n",
  "-- Migration: Add password authentication columns to users table\n-- Run this in Supabase SQL Editor\n-- Safe to run — all new columns are nullable\n\nALTER TABLE \"users\"\n  ADD COLUMN IF NOT EXISTS \"password_hash\" text,\n  ADD COLUMN IF NOT EXISTS \"password_set_at\" timestamp with time zone,\n  ADD COLUMN IF NOT EXISTS \"password_attempts\" integer DEFAULT 0,\n  ADD COLUMN IF NOT EXISTS \"password_locked_until\" timestamp with time zone;\n"
];

export const BOOTSTRAP_ALTERS: string[] = [
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"adminPhone\" text;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"type\" text;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"channel\" text;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"title\" text;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"body\" text;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"status\" text;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"key\" text;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"value\" text;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"count\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"lastSeenAt\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"syncedAt\" timestamp with time zone;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"actorStaffMemberId\" bigint;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"actorDeviceId\" text;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"action\" text;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"entityType\" text;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"entityId\" text;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"blockedPermission\" text;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"details\" text;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"bankName\" text;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"bankUserId\" bigint;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"shareSalesData\" boolean;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"shareCreditData\" boolean;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"shareCustomerData\" boolean;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"status\" text;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"consentGivenAt\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"consentRevokedAt\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"expiresAt\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"notes\" text;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"updatedAt\" timestamp with time zone;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"bankDataShareId\" bigint;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"reportVersion\" bigint;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"payload\" jsonb;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"generatedAt\" timestamp with time zone;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"expiresAt\" timestamp with time zone;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"phoneNumber\" text;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"displayName\" text;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"bankName\" text;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"bankRole\" text;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"active\" boolean;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"userId\" bigint;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"displayName\" text;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"role\" text;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"permissions\" jsonb;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"invitedByUserId\" bigint;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"joinedAt\" timestamp with time zone;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"active\" boolean;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"ownerUserId\" bigint;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"name\" text;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"slug\" text;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"preferredLang\" text;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"phoneRequired\" boolean;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"approvalRequired\" boolean;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"plan\" text;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"updatedAt\" timestamp with time zone;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"localId\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"transactionId\" text;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"name\" text;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"kind\" text;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"active\" boolean;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"defaultPrice\" double precision;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"defaultCost\" double precision;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"note\" text;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"syncedAt\" timestamp with time zone;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"localId\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"transactionId\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"customerId\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"amount\" double precision;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"type\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"note\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"itemNote\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"dueDate\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"referenceCode\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"telegramDeliveryState\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"telegramDeliveryError\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"telegramDeliveryAttemptedAt\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"year\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"categoryCode\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"labelCode\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"syncedAt\" timestamp with time zone;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"localId\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"transactionId\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"name\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"email\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"address\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"active\" boolean;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"totalPurchases\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"lastPurchaseAt\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"note\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegramChatId\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegramLinkRequestedAt\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"displayName\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"phoneNumber\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegramUsername\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegramNotifyEnabled\" boolean;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegramLinkToken\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegramLinkedAt\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"syncedAt\" timestamp with time zone;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"userId\" bigint;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"tokenHash\" text;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"shopId\" bigint;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"staffId\" bigint;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"name\" text;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"status\" text;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"lastSeenAt\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"invitedByUserId\" bigint;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"phoneNumber\" text;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"staffName\" text;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"role\" text;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"token\" text;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"notificationSent\" boolean;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"notificationMethod\" text;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"expiresAt\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"acceptedAt\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"declinedAt\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"revokedAt\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"ownerUserId\" bigint;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"type\" text;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"title\" text;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"body\" text;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"entityType\" text;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"entityId\" text;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"actorName\" text;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"amount\" double precision;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"read\" boolean;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"phoneNumber\" text;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"codeHash\" text;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"attempts\" bigint;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"maxAttempts\" bigint;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"expiresAt\" timestamp with time zone;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"consumed\" boolean;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"platform_admin_members\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"platform_admin_members\" ADD COLUMN IF NOT EXISTS \"phone\" text;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"email\" text;",
  "ALTER TABLE \"platform_admin_members\" ADD COLUMN IF NOT EXISTS \"email\" text;",
  "ALTER TABLE \"platform_admin_members\" ADD COLUMN IF NOT EXISTS \"addedByPhone\" text;",
  "ALTER TABLE \"platform_admin_members\" ADD COLUMN IF NOT EXISTS \"note\" text;",
  "ALTER TABLE \"platform_admin_members\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"userId\" bigint;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"endpoint\" text;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"p256dh\" text;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"auth\" text;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"userAgent\" text;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"key\" text;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"value\" text;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"syncedAt\" timestamp with time zone;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"localId\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"settlementId\" text;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staffId\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"periodStart\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"periodEnd\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"expectedCash\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"actualCash\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"cashVariance\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"expectedTransfer\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"actualTransfer\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"transferVariance\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"expectedTotal\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"actualTotal\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"totalVariance\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"adjustments\" jsonb;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"finalExpectedCash\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"finalExpectedTotal\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"finalVariance\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"status\" text;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"notes\" text;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"settledAt\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"settledBy\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciledAt\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciledBy\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciliationNote\" text;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciliationStatus\" text;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staffReportedCash\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staffReportedTransfer\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staffSubmittedAt\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staffNote\" text;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"ownerConfirmedCash\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"ownerConfirmedTransfer\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"ownerNote\" text;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciliationLog\" jsonb;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"carryForward\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"userId\" bigint;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"name\" text;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"description\" text;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"sizeBytes\" bigint;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"tables\" text;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"recordCount\" bigint;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"checksum\" text;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"payload\" text;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"staffId\" bigint;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"clockIn\" timestamp with time zone;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"clockOut\" timestamp with time zone;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"notes\" text;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"userId\" bigint;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"clientEventId\" text;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"recordId\" text;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"actorNameSnapshot\" text;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"actorRoleAtEvent\" text;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"eventType\" text;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"occurredAtDevice\" timestamp with time zone;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"payload\" jsonb;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"localId\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"transactionId\" text;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"displayName\" text;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"role\" text;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"active\" boolean;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"deactivatedAt\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"syncedAt\" timestamp with time zone;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"staffId\" bigint;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"title\" text;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"description\" text;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"priority\" text;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"status\" text;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"dueDate\" timestamp with time zone;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"completedAt\" timestamp with time zone;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"createdBy\" bigint;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"updatedAt\" timestamp with time zone;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"localId\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"transactionId\" text;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"supplierId\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"amount\" double precision;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"type\" text;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"note\" text;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"itemName\" text;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"itemKind\" text;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"quantity\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"deletedAt\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"syncedAt\" timestamp with time zone;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"localId\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"transactionId\" text;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"displayName\" text;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"phoneNumber\" text;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"note\" text;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"active\" boolean;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"deletedAt\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"syncedAt\" timestamp with time zone;",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"ticketId\" bigint;",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"senderUserId\" bigint;",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"senderRole\" text;",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"body\" text;",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"ownerUserId\" bigint;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"subject\" text;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"description\" text;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"status\" text;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"priority\" text;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"updatedAt\" timestamp with time zone;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"resolvedAt\" timestamp with time zone;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"resolvedByUserId\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"localId\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"deviceId\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"transactionId\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"type\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"amount\" double precision;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"itemName\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"costPrice\" double precision;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"quantity\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"profit\" double precision;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"isCredit\" boolean;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"customerId\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"customerName\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"createdAt\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"updatedAt\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"ethiopianDate\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"labelCode\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"paymentType\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"paymentProvider\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"saleSettlementMode\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"paidAmount\" double precision;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"remainingAmount\" double precision;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"settlementDueDate\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"source\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"wasEdited\" boolean;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"actorRole\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"actorStaffMemberId\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"actorNameSnapshot\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"deletedAt\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"businessId\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"schemaVersion\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"syncVersion\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"syncedAt\" timestamp with time zone;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"id\" bigint;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"phoneNumber\" text;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"active\" boolean;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"preferredLang\" text;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"telegramChatId\" text;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"telegramLinkToken\" text;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"passwordHash\" text;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"passwordSetAt\" timestamp with time zone;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"passwordAttempts\" bigint;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"passwordLockedUntil\" timestamp with time zone;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"createdAt\" timestamp with time zone;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"local_id\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"transaction_id\" varchar(128);",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"item_name\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"cost_price\" real;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"is_credit\" boolean;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"customer_id\" integer;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"customer_name\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"ethiopian_date\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"payment_type\" varchar(64);",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"payment_provider\" varchar(64);",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"sale_settlement_mode\" varchar(32);",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"paid_amount\" real;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"remaining_amount\" real;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"settlement_due_date\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"was_edited\" boolean;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"actor_role\" varchar(32);",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"actor_staff_member_id\" integer;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"actor_name_snapshot\" text;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"deleted_at\" bigint;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"transactions\" ADD COLUMN IF NOT EXISTS \"synced_at\" timestamp with time zone;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"local_id\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"transaction_id\" varchar(128);",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"total_purchases\" integer;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"last_purchase_at\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegram_chat_id\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegram_link_requested_at\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"display_name\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"phone_number\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegram_username\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegram_notify_enabled\" boolean;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegram_link_token\" text;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"telegram_linked_at\" bigint;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"customers\" ADD COLUMN IF NOT EXISTS \"synced_at\" timestamp with time zone;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"local_id\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"transaction_id\" varchar(128);",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"customer_id\" integer;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"item_note\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"due_date\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"reference_code\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"telegram_delivery_state\" varchar(32);",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"telegram_delivery_error\" text;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"telegram_delivery_attempted_at\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"customer_transactions\" ADD COLUMN IF NOT EXISTS \"synced_at\" timestamp with time zone;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"local_id\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"transaction_id\" varchar(128);",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"default_price\" real;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"default_cost\" real;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"catalog_entries\" ADD COLUMN IF NOT EXISTS \"synced_at\" timestamp with time zone;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"local_id\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"transaction_id\" varchar(128);",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"display_name\" text;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"phone_number\" text;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"deleted_at\" bigint;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"suppliers\" ADD COLUMN IF NOT EXISTS \"synced_at\" timestamp with time zone;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"local_id\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"transaction_id\" varchar(128);",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"supplier_id\" integer;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"item_name\" text;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"item_kind\" varchar(32);",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"deleted_at\" bigint;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"supplier_transactions\" ADD COLUMN IF NOT EXISTS \"synced_at\" timestamp with time zone;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"local_id\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"transaction_id\" varchar(128);",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"display_name\" text;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"deactivated_at\" bigint;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"phone_snapshot\" varchar(32);",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"staff_members\" ADD COLUMN IF NOT EXISTS \"synced_at\" timestamp with time zone;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"synced_at\" timestamp with time zone;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"last_seen_at\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"analytics\" ADD COLUMN IF NOT EXISTS \"synced_at\" timestamp with time zone;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"user_id\" integer;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"token_hash\" varchar(64);",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"shop_id\" integer;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"staff_id\" integer;",
  "ALTER TABLE \"devices\" ADD COLUMN IF NOT EXISTS \"last_seen_at\" timestamp with time zone;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"phone_number\" text;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"preferred_lang\" varchar(8);",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"telegram_chat_id\" text;",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"phone_number\" text;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"code_hash\" text;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"max_attempts\" integer;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"expires_at\" timestamp with time zone;",
  "ALTER TABLE \"otps\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"user_id\" integer;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"size_bytes\" integer;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"record_count\" integer;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"snapshots\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"owner_user_id\" integer;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"preferred_lang\" varchar(8);",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"phone_required\" boolean;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"approval_required\" boolean;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"businesses\" ADD COLUMN IF NOT EXISTS \"updated_at\" timestamp with time zone;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"user_id\" integer;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"display_name\" text;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"invited_by_user_id\" integer;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"joined_at\" timestamp with time zone;",
  "ALTER TABLE \"business_members\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"invited_by_user_id\" integer;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"phone_number\" text;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"staff_name\" text;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"notification_sent\" boolean;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"notification_method\" varchar(32);",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"expires_at\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"accepted_at\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"declined_at\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"revoked_at\" timestamp with time zone;",
  "ALTER TABLE \"invites\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"actor_staff_member_id\" integer;",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"actor_device_id\" varchar(128);",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"entity_type\" varchar(64);",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"entity_id\" varchar(128);",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"blocked_permission\" varchar(64);",
  "ALTER TABLE \"audit_log\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"owner_user_id\" integer;",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"entity_type\" varchar(64);",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"entity_id\" varchar(128);",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"actor_name\" varchar(128);",
  "ALTER TABLE \"notifications\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"user_id\" integer;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"user_agent\" text;",
  "ALTER TABLE \"push_subscriptions\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"user_id\" integer;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"client_event_id\" varchar(128);",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"record_id\" varchar(128);",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"actor_name_snapshot\" text;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"actor_role_at_event\" varchar(32);",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"event_type\" varchar(32);",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"occurred_at_device\" timestamp with time zone;",
  "ALTER TABLE \"staff_events\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"staff_id\" integer;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"due_date\" timestamp with time zone;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"completed_at\" timestamp with time zone;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"created_by\" integer;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"staff_tasks\" ADD COLUMN IF NOT EXISTS \"updated_at\" timestamp with time zone;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"staff_id\" integer;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"clock_in\" timestamp with time zone;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"clock_out\" timestamp with time zone;",
  "ALTER TABLE \"staff_attendance\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"bank_name\" varchar(128);",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"bank_user_id\" integer;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"share_sales_data\" boolean;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"share_credit_data\" boolean;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"share_customer_data\" boolean;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"consent_given_at\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"consent_revoked_at\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"expires_at\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"bank_data_shares\" ADD COLUMN IF NOT EXISTS \"updated_at\" timestamp with time zone;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"bank_data_share_id\" integer;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"report_version\" integer;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"generated_at\" timestamp with time zone;",
  "ALTER TABLE \"bank_report_snapshots\" ADD COLUMN IF NOT EXISTS \"expires_at\" timestamp with time zone;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"phone_number\" text;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"display_name\" text;",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"bank_name\" varchar(128);",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"bank_role\" varchar(32);",
  "ALTER TABLE \"bank_users\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp with time zone;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"local_id\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"device_id\" varchar(128);",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"settlement_id\" varchar(128);",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staff_id\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"period_start\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"period_end\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"expected_cash\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"actual_cash\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"cash_variance\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"expected_transfer\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"actual_transfer\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"transfer_variance\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"expected_total\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"actual_total\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"total_variance\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"final_expected_cash\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"final_expected_total\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"final_variance\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"settled_at\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"settled_by\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciled_at\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciled_by\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciliation_note\" varchar(500);",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciliation_status\" varchar(32);",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staff_reported_cash\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staff_reported_transfer\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staff_submitted_at\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"staff_note\" varchar(500);",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"owner_confirmed_cash\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"owner_confirmed_transfer\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"owner_note\" varchar(500);",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"reconciliation_log\" jsonb;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"carry_forward\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"created_at\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"updated_at\" bigint;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"sync_version\" integer;",
  "ALTER TABLE \"settlements\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"owner_user_id\" integer;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamptz;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"updated_at\" timestamptz;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"resolved_at\" timestamptz;",
  "ALTER TABLE \"support_tickets\" ADD COLUMN IF NOT EXISTS \"resolved_by_user_id\" integer;",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"ticket_id\" integer;",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"sender_user_id\" integer;",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"sender_role\" varchar(32);",
  "ALTER TABLE \"support_messages\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamptz;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"business_id\" integer;",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"admin_phone\" varchar(32);",
  "ALTER TABLE \"admin_shop_logs\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp;",
  "ALTER TABLE \"platform_admin_members\" ADD COLUMN IF NOT EXISTS \"added_by_phone\" text;",
  "ALTER TABLE \"platform_admin_members\" ADD COLUMN IF NOT EXISTS \"created_at\" timestamp;"
];
